### ISSUE TITLE
可以送我一些下载API吗

### ISSUE THREAD

**Issue by zimoyin** [nICEnnnnnnnLee/BilibiliDown#103]
我找到的API都是需要设置ref的，我需要一些不需要设置 ref（防盗链）的API。

**Comment by nICEnnnnnnnLee** [comment]
```
https://www.bilibili.com/blackboard/html5mobileplayer.html?aid=932160271&bvid=BV1LM4y1K7Ms&cid=384624341&page=1&high_quality=1&posterFirst=1
```

**Comment by zimoyin** [comment]
> ```
> https://www.bilibili.com/blackboard/html5mobileplayer.html?aid=932160271&bvid=BV1LM4y1K7Ms&cid=384624341&page=1&high_quality=1&posterFirst=1
> ```

感谢大佬
