### ISSUE TITLE
Linux 系统下按钮字体锯齿严重，建议添加抗锯齿设置。

### ISSUE THREAD

**Issue by blickers** [nICEnnnnnnnLee/BilibiliDown#107]
**我已经确认**
- 使用的当前版本为最新版本
- issue区没有类似的情况（有的话请直接去该问题讨论）

**问题描述**
可能作者没有在 Linux 系统下测试过这个软件。根据我在 Ubuntu 22.04 下的测试，软件 UI 按钮的字体没有启用抗锯齿，看起来非常难看。建议增加抗锯齿代码。

问题出在 src/nicelee/ui/item/MJButton.java 这个文件里，解决的办法如下：

增加
import java.awt.Graphics2D;
import java.awt.RenderingHints;

public void paint(Graphics g, JComponent c) 修改为 public void paint(Graphics2D g, JComponent c)

另外在 FontMetrics fm = g.getFontMetrics(); 这一行后面增加一行：
g.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING,RenderingHints.VALUE_TEXT_ANTIALIAS_ON);

可以完美解决 Linux 下按钮字体锯齿严重，看起来很丑陋的问题，请求作者修正。

另外软件 UI 其实不用自己设置顶部标题栏、关闭、最小化按钮等，交给操作系统去处理。否则这些 UI 元素不跟随操作系统主题，与操作系统主题格格不入，很难看，特别是在 macOS 和 Linux （调用系统 gtk 主题）下。建议作者考虑去掉这些元素。

**相关信息**
+ 当前系统(windows/linux等)：Ubuntu 22.04
+ java版本：openjdk-11-jdk:amd64 11.0.15+10-0ubuntu0.22.04.1

**Comment by blickers** [comment]
关于软件在 macOS 和 Linux 下窗口标题栏、最小化、关闭按钮及颜色的问题，见图片：
![1](https://user-images.githubusercontent.com/54505861/182810417-f35cdc86-b183-456c-ac14-667562bd0c8a.png)

建议较个操作系统处理软件边框、标题栏和和最小化、关闭按钮。

**Comment by nICEnnnnnnnLee** [comment]
首先得承认，界面这一块确实很挫。
<hr/>

> 
>    Linux 系统下按钮字体锯齿严重
> 


这个可以改
 <hr/>

>
> 不用自己设置顶部标题栏、关闭、最小化按钮等    
>

   这个是有历史原因的，如果要把`操作|配置|关于`菜单移到顶部，只能自定义标题栏。  
   ![menu2titlebar](https://user-images.githubusercontent.com/19970934/183007674-e2205f7b-4a51-4c82-b723-fdef3f6c8579.png)
   
   我并不觉得自定义标题栏有什么不好，它的风格确实和MacOS不搭，但没有到需要回退的地步。  
   如果你实在需要，可以将主类从`nicelee.ui.FrameMain`改为`nicelee.ui.FrameMain_v3_4`看看效果  
(当然功能可能随着版本迭代已经出现问题)。  
   ```
   java -Dfile.encoding=utf-8 -cp INeedBiliAV.jar nicelee.ui.FrameMain_v3_4
   ```
   我可以恢复对`nicelee.ui.FrameMain_v3_4`的功能支持，但不会为此再做更多。  
 <hr/>

>
> 调用系统主题，只有部分跟随系统主题变化...
>

+ 首先，经测试在Ubuntu22.04 open-jdk11深色模式下，程序显示基本上和浅色模式没啥区别。    
  ![dark-mode2](https://user-images.githubusercontent.com/19970934/183007618-cb849c2d-2d1a-4543-9b1e-bc174243f50f.png)
    我认为程序显示在深色/浅色模式下一样是符合预期的。  
   上面部分适配的情况应该是配置或者代码做了改动，或者说Java Swing的这部分实现可能是针对Mac？？
  

+ 另外，这实际上是一个新的需求，即适配深色模式Dark mode。  
    我可以说，即使是不自定义button、标题栏，全都交给系统，仍然有地方需要适配。  
    同时，那也只是换种丑法。  
    你可以将试试配置`bilibili.button.style = default`，看看长得咋样。  
    我认为这会有一个较大的工作量，大到我宁愿推倒重来。我不会再用Swing，亦或者JavaFX；如果再要写多平台界面，我会选择electron，或者做个本地服务器+前端，通过浏览器操作。  
    **我不会为此做更多改动**

**Comment by blickers** [comment]
可能是各人喜好吧，你把 UI 弄得太“花俏”了，那些背景图片，看得眼花。
我一顿修改，把默认界面还原成一般软件常见的朴素样子，感觉看起来顺眼很多。让 UI 主题默认跟随系统主题变化，它能自己适应白天模式和暗夜模式，看截图：
![0-2](https://user-images.githubusercontent.com/54505861/183412084-224c2b41-2ade-4413-b987-942fe3498092.png)
![0](https://user-images.githubusercontent.com/54505861/183412335-37dd471b-e789-4204-9c3e-bc3ab8ab2845.png)
![1-2](https://user-images.githubusercontent.com/54505861/183412505-86cde785-d460-4d09-8ff4-6fa8cc2acc0f.png)
![1](https://user-images.githubusercontent.com/54505861/183412454-eeb99def-8e6f-4140-bf35-9b1a2513ef50.png)
![2](https://user-images.githubusercontent.com/54505861/183412553-14a561f6-b8f3-47b5-8708-14f919007dc2.png)

**Comment by blickers** [comment]
我直接改了 FrameMain.java，并没有使用 FrameMain_v3_4.java

关于配置文件路径、下载保存路径，我觉得也很有问题，没有考虑到不同操作系统的处理，建议增加一些代码，判断操作系统类型，按不同操作系统，调用不同的默认路径。

比如，Linux 系统下，默认 app.config 应该保存到 /etc/BilibiliDown 下，user.config 应该保存到 ~/.config/BilibiliDown  下，默认下载目录为 ~/Downloads

macOS 系统下，app.config 保存到 /Library/'Application Support'/BilibiliDown 下， user.config 应该保存到 ~/Library/'Application Support'/BilibiliDown 下，，默认下载目录为 ~/Downloads

Windows 下也不建议将默认下载路径设置为当前路径下的 ./download

还有一个问题是 Linux、macOS 下制作 jar 包的 package.sh 用的是 Windows 换行符，在 Linux/macOS 下会出问题。建议用 dos2unix 处理一下，换上去，更新掉源码库里的原文件。
