### ISSUE TITLE
建议Gitee工程上同步发行release

### ISSUE THREAD

**Issue by iamPorter** [nICEnnnnnnnLee/BilibiliDown#108]
如果Gitee上位于“NiceLee/BilibiliDown”的工程是您自己安排的镜像工程，建议也同时同步发行release，毕竟访问GitHub不是很方便，下载速度也很慢，且您的工程小于100MB，理论上是可以顺利在Gitee上推出发行版的。
虽然程序已经被您散发在了master目录下了，但是为了下一个程序把整套master下载下来总显得有些多余。仍烦请辛苦一下谢谢！

**Comment by nICEnnnnnnnLee** [comment]
> 虽然程序已经被您散发在了master目录下了，但是为了下一个程序把整套master下载下来总显得有些多余

。。。
工程下的整个`release`文件夹，大体上对标的是release下附件解压后的结果。  
里面的主程序只是一个示例，已经很久没更新了。 
**正确的下载方法**是前往[release页面](https://github.com/nICEnnnnnnnLee/BilibiliDown/releases)根据需要下载附件。
附件大小1MB左右，下载速度再慢我想也能接受吧。  
而且这个操作只需要进行一次，之后程序本身是写了版本更新的功能的。  

另外，如果你觉得访问Github成本过高：
镜像： https://hub.fastgit.xyz/
附件代理加速：https://ghproxy.com/
通过cloudflare workers免费部署Github镜像： https://github.com/nICEnnnnnnnLee/GithubSoEasy/
至于如何科学的越过GFW我就不提了。
