### ISSUE TITLE
分多季的列表会只提取一个视频

### ISSUE THREAD

**Issue by baozugong** [nICEnnnnnnnLee/BilibiliDown#115]
**我已经确认**
- 使用的当前版本为最新版本
- issue区没有类似的情况（有的话请直接去该问题讨论）

**问题描述**
在识别分季的列表时，只能提取到一个视频，而且视频标题有误。

**相关信息**
+ 系统：win10家庭版   版本号：21H1   内部版本：19043.2006
+ java版本： JDK 18.0.2.1
+ 相关链接或者BV号：(https://www.bilibili.com/video/BV1fL4y1Y73r/)
+ 没有登录账号
+ 网页端可以观看，页面右侧为一个列表，列表分为两季，每季下有多集
+ 是否存在自定义parsers：不懂
+ 相关log：不懂
```
感谢作者大佬分享的软件，相当好用。
我是小白，不懂程序，不知道parsers是啥，不知道也不知道哪看日志，希望没有给作者大佬带来不便。
顺便问问转换仓库是什么意思？
```

**Comment by baozugong** [comment]
补充一下，视频标题有误是指软件右侧的每个视频的标题有误。

**Comment by nICEnnnnnnnLee** [comment]
下载合集请使用合集链接 https://space.bilibili.com/7942241/channel/collectiondetail?sid=28106

**Comment by nICEnnnnnnnLee** [comment]
> 顺便问问转换仓库是什么意思？

这是一个历史遗留功能，目的是将老版本的`repo.config`中的下载记录由av转化为BV的形式。
B站实施BV这么久了，这个功能应该基本上用不到了
