### ISSUE TITLE
Feature Request - 请支持把下载文件放到一个文件夹

### ISSUE THREAD

**Issue by anson2416** [nICEnnnnnnnLee/BilibiliDown#118]
Hi, 谢谢你的软件!

现在App会把所有下载的文件放到 同一个作者为名字命名的**一个文件夹**.  能不能设置一个功能把视频下载到 以视频名字的文件夹里面? 

谢谢.

**Comment by nICEnnnnnnnLee** [comment]
[如何自定义文件名 ](https://nICEnnnnnnnLee.github.io/BilibiliDown/guide/advanced/custom-file-name)
```
# 不包含小标题
bilibili.name.format = avTitle-pAv2-qn
# 包含小标题
bilibili.name.format = avTitle-clipTitle-pAv2-qn
```

**Comment by anson2416** [comment]
你好, 我把 自定义文件名其中的变量 `avTitle` 放到 `bilibili.savePath` 不生效. 

https://nicelee.top/BilibiliDown/guide/advanced/custom-file-path

**Comment by nICEnnnnnnnLee** [comment]
我在二楼由易到难举了三个例子，第三个就是答案。
