### ISSUE TITLE
下载失败问题

### ISSUE THREAD

**Issue by dfmjndm** [nICEnnnnnnnLee/BilibiliDown#120]
windows最新版本，在下载收藏夹视频的时候开了几十个页面然后批量下载标签页，下了一段时间发现除了开始的20个视频，后面的全部报错下载异常，任务状态为暂停，下载进度未知，使用全部重试也无效。只能删除所有下载任务，再重新点批量下载标签页。
猜测是任务新建太早，获取的链接还没轮到下载就失效了，这样的话需要限制等待状态的任务数量，让其他视频先不解析？
我该如何长时间的下载收藏夹内容。

**Comment by nICEnnnnnnnLee** [comment]
> 猜测是任务新建太早，获取的链接还没轮到下载就失效了，这样的话需要限制等待状态的任务数量，让其他视频先不解析？

链接是开始下载的时候查询的，不存在失效问题。也就是在等待队列多久都没问题。

需要注意的是，如果已经从等待队列出来，并查询到了链接，之后点暂停或重试都是原来的链接，这时可能会过期

**Comment by nICEnnnnnnnLee** [comment]
> 只能删除所有下载任务，再重新点批量下载标签页。

你可以在菜单保存下载面板的下载任务，清空后重新加载

**Comment by nICEnnnnnnnLee** [comment]
> windows最新版本，在下载收藏夹视频的时候开了几十个页面然后批量下载标签页，下了一段时间发现除了开始的20个视频，后面的全部报错下载异常，任务状态为暂停，下载进度未知，使用全部重试也无效。只能删除所有下载任务，再重新点批量下载标签页。 猜测是任务新建太早，获取的链接还没轮到下载就失效了，这样的话需要限制等待状态的任务数量，让其他视频先不解析？ 我该如何长时间的下载收藏夹内容。

这种情况能否稳定复现？ 能的话请提供log，最开始批量失败前后的以及重试报错的。如果没法区分请重定向输出到文件并提供该文件

**Comment by dfmjndm** [comment]
昨天晚上又试了一下，下载池线程大小为2，并行下载数量一开始是2，然后早上起来发现下载中数量已经是几百个了。晚些时间我开下log再试下![Screenshot_2022-10-29-12-29-23-231_com.microsoft.rdc.androidx.jpg](https://user-images.githubusercontent.com/57401901/198813947-7f12813d-9d85-4993-b636-f71b3316da97.jpg)
