### ISSUE TITLE
断点重连问题

### ISSUE THREAD

**Issue by dfmjndm** [nICEnnnnnnnLee/BilibiliDown#121]
想问下对于下载一半手动暂停，然后删除任务的对象
重新下载是会断点重连还是整个视频重新下载还是显示”视频已存在“
是否会因为点击跳过造成不完整的视频存在
因为情况与wiki略有不同故再问一下
![image](https://user-images.githubusercontent.com/57401901/198684318-a89a8e4d-231d-4d63-b65f-f6176f5ea969.png)

**Comment by nICEnnnnnnnLee** [comment]
只要视频没有下载成功过，就不会保存下载记录，就不会弹出已下载。

**Comment by nICEnnnnnnnLee** [comment]
> 是否会因为点击跳过造成不完整的视频存在

我没太理解你的意思？
只可能会有不完整的临时文件，不可能会有不完整的最终视频，除非出bug。

**Comment by dfmjndm** [comment]
> > 是否会因为点击跳过造成不完整的视频存在
> 
> 我没太理解你的意思？
> 只可能会有不完整的临时文件，不可能会有不完整的最终视频，除非出bug。
> 
> 删除任务对象并不会删除临时文件，这种情况产生的临时文件需要人工进行删除

好的我理解了
