### ISSUE TITLE
下载的视频编码可否加入av1选项

### ISSUE THREAD

**Issue by malviez** [nICEnnnnnnnLee/BilibiliDown#122]
b站页面现在可选av1编码，4k视频能省很多空间，期待加入这个功能。

**Comment by nICEnnnnnnnLee** [comment]
<https://github.com/nICEnnnnnnnLee/BilibiliDown/actions/runs/3349792371>
`dev`分支已经实现了编码选择优先级，只需要适当修改配置，并且ffmpeg版本较新，就可以下av1的
https://github.com/nICEnnnnnnnLee/BilibiliDown/blob/57743f94c0b6192b748aef17336800761f4bb1e8/release/config/app.config#L49-L72
