### ISSUE TITLE
不能通过导入视频链接的方式下载吗

### ISSUE THREAD

**Issue by Jieoz** [nICEnnnnnnnLee/BilibiliDown#123]
有一堆bv号的列表用这个软件就没办法批量下载吧

**Comment by nICEnnnnnnnLee** [comment]
https://nicennnnnnnlee.github.io/BilibiliDown/guide/frequently-asked/how-to-redownload-videos#%E6%9C%80%E5%90%8E%EF%BC%8C%E4%BD%BF%E7%94%A8%E4%B8%80%E9%94%AE%E4%B8%8B%E8%BD%BD%E5%8A%9F%E8%83%BD%E8%A1%A5%E5%85%85%E4%B8%8B%E8%BD%BD%E6%8C%87%E5%AE%9A%E5%86%85%E5%AE%B9%E3%80%82
