### ISSUE TITLE
作品信息页面文字乱码

### ISSUE THREAD

**Issue by sr093906** [nICEnnnnnnnLee/BilibiliDown#127]
**我已经确认**
- 使用的当前版本为最新版本
- issue区没有类似的情况（有的话请直接去该问题讨论）

**问题描述**
作品信息页面文字乱码

**相关信息**
+ Windows 10
+ Java 8 Update 351
+ 相关链接或者BV号
+ 未登录
+ 在网页端观看是否存在问题
+ 是否存在自定义parsers
+ 无
  + 如何抓log请参考[Wiki-How to log](https://github.com/nICEnnnnnnnLee/BilibiliDown/wiki/How-to-log)

```
我不确定是否是程序问题。另外，不知道是否可以进行捐赠表达感谢。
```
![1](https://user-images.githubusercontent.com/8369201/204086721-57c066dd-0f0c-48ab-b08a-1407d1f15aab.PNG)

**Comment by nICEnnnnnnnLee** [comment]
运行的时候要指定utf-8编码`-Dfile.encoding=utf-8 `。  
建议创建快捷方式，或者双击脚本`Double-Click-to-Run-for-Win.bat`运行。  
参考<https://nICEnnnnnnnLee.github.io/BilibiliDown/guide/quick-start/run>

**Comment by nICEnnnnnnnLee** [comment]
感谢的话，点个Star就行了
