### ISSUE TITLE
可否增加bilibili 音频区 的下载功能 就au****的

### ISSUE THREAD

**Issue by 2651084156** [nICEnnnnnnnLee/BilibiliDown#131]
可否增加bilibili 音频区 的下载功能 就au****的

**Comment by 2651084156** [comment]
![图片](https://user-images.githubusercontent.com/69307837/210200730-c55e54a3-6f24-4b83-917f-7629f6b5e2f8.png)
新版本清晰度获取貌似有问题

**Comment by 2651084156** [comment]
6.22

**Comment by 2651084156** [comment]
从合集获取会出现这种情况 单独不会

**Comment by nICEnnnnnnnLee** [comment]
> 从合集获取会出现这种情况 单独不会

从合集获取使用的API和单独的不一样。如果要获取实际清晰度，需要每个视频再进行一次查询。  
考虑到`查询不存在的高码率视频，会得到次一档码率的存在的视频`，没有必要再增加网络请求，直接把可能的清晰度列出。
