### ISSUE TITLE
可否增加一键下载一堆单独视频链接功能？

### ISSUE THREAD

**Issue by lilocici** [nICEnnnnnnnLee/BilibiliDown#134]
就是像现在的一键下载功能，可以批量下载链接，但是是针对一堆单独的视频链接。

例如提供一堆链接，里面有这些视频链接：
	bv111111
	https://www.bilibili.com/video/bv222222
	https://www.bilibili.com/video/bv333333

然后一键下载可以逐个顺序的下载这些视频（非一次性全部解析加载）。

**Comment by nICEnnnnnnnLee** [comment]
https://nicennnnnnnlee.github.io/BilibiliDown/guide/frequently-asked/how-to-redownload-videos#%E6%9C%80%E5%90%8E%EF%BC%8C%E4%BD%BF%E7%94%A8%E4%B8%80%E9%94%AE%E4%B8%8B%E8%BD%BD%E5%8A%9F%E8%83%BD%E8%A1%A5%E5%85%85%E4%B8%8B%E8%BD%BD%E6%8C%87%E5%AE%9A%E5%86%85%E5%AE%B9%E3%80%82

**Comment by lilocici** [comment]
哦，收到！感谢，原来一键下载有额外的功能，然后说明藏在另一个地方。

不过，是必须每一个 url 都写一遍那些下面的参数吗，例如：

[url:BV1Yf4y1K7Gs]
stop.condition = _!_
download.condition = _:_
stop.alert = false

[url:BV1Ag411U7nf]
stop.condition = _!_
download.condition = _:_
stop.alert = false

这些例如 stop.condition download.condition 等参数必须要每个 url 都写一次吗？

不知道可否简单一些，例如直接提供一个 txt 文件里面包含链接，然后参数只需写一遍，例如：

[txt:d:/bilibili/urllist.txt]
stop.condition = _!_
download.condition = _:_
stop.alert = false

不知道这个功能可行不？

**Comment by nICEnnnnnnnLee** [comment]
> 这些例如 stop.condition download.condition 等参数必须要每个 url 都写一次吗？
> 

必须要写

> 不知道这个功能可行不？

没有计划实现这个功能。包括像现在的非分页查询的功能，原本也是没有打算实现的。  
为了解决api变化导致的低糊视频下载过多的问题，才加的这个功能。

**Comment by lilocici** [comment]
好的，知道啦
