### ISSUE TITLE
提示程序已经在运行

### ISSUE THREAD

**Issue by malviez** [nICEnnnnnnnLee/BilibiliDown#135]
电脑死机后再打开就提示“程序已经在运行！”，但是找不到进程，没法重新打开了。

**Comment by nICEnnnnnnnLee** [comment]
`config`文件夹下应该会有`.lock`文件，把它删除即可

或者在app.config配置文件中设置`bilibili.lockCheck=false`取消检查

**Comment by malviez** [comment]
好的
