### ISSUE TITLE
哪个傻屌写的Uninstall脚本？

### ISSUE THREAD

**Issue by watertang** [nICEnnnnnnnLee/BilibiliDown#140]
你压缩不带路径我不能怪你，虽然一堆文件污染了我的下载目录，我逐个手动删除还是可以的。但我手贱按了Uninstall.bat，结果tmd我下载目录下的全部文件和目录都被你删得一干二净，还不带回收站的那种，我就想cao你全家知道吗？

**Comment by watertang** [comment]
你自身带什么文件你就删什么文件，这个才叫Uninstall！！！ `rd /s /q  %~dp0` 叫做破坏！！！懂吗？！

**Comment by nICEnnnnnnnLee** [comment]
+ 在不知道压缩包具体内容的情况下，最稳健的策略是先查看其内容或者解压到压缩包同名文件夹。  
基于这一策略，顶层打包可以减少不必要的文件夹层数。

  
+ 除了配置的下载文件夹以及可能的快捷方式，理论上程序相关的文件均应在jar包/脚本所在目录下。  
正常情况下，程序应当被安置在独立的文件夹中运行，即目录不存在其它不相关的文件。  
此时，`rd /s /q  %~dp0`，即清空脚本所在目录，可以恰当地卸载程序，与具体到个别文件删除效果等同，而不必花功夫管理文件列表，后续每次版本更新时都需要跟踪。  
为了防止误点击，在执行语句前需要输入`y`进行确认。
