### ISSUE TITLE
不同分辨率的不能下载

### ISSUE THREAD

**Issue by JimmyKent** [nICEnnnnnnnLee/BilibiliDown#141]
我默认勾选1080分辨率的，如果没有1080分辨率，就显示找不到源
<img width="495" alt="32676361f5089259ae4cf145f" src="https://user-images.githubusercontent.com/17265973/231059549-4707cc78-5972-46b9-b8f4-c86565b71d83.png">

**Comment by nICEnnnnnnnLee** [comment]
当前程序的逻辑是这样的，在当前已登录的情况下，若查询的实际分辨率小于预期的分辨率，且画质模糊(清晰度为480P及以下)，那么抛出异常。

这样做的目的是防止API变动导致下载了非预期的模糊视频而不自知。考虑到最高画质为480P的视频较为少见，遂抛出异常。

在下个版本会增加相关配置，可以开启/关闭该判断逻辑
