### ISSUE TITLE
如果视频是需要会员收费的，是否就无法下载？

### ISSUE THREAD

**Issue by RobertChou** [nICEnnnnnnnLee/BilibiliDown#144]
**我已经确认**
- 使用的当前版本为最新版本
- 使用最新的CI版本仍然存在该问题[CI传送门](https://github.com/nICEnnnnnnnLee/BilibiliDown/actions/workflows/pre-release-artifacts.yml)
- issue区没有类似的情况（有的话请直接去该问题讨论）

**问题描述**
课程区有不少课程是要收费的，比如https://www.bilibili.com/cheese/play/ss990
试看的只能下载5分钟，其他分集无法下载？

**相关信息**
+ 当前系统(windows/linux等)
+ java版本
+ 相关链接或者BV号
+ 账号是否登录
+ 在网页端观看是否存在问题
+ 是否存在自定义parsers
+ 相关log
  + 如何抓log请参考[Wiki-How to log](https://github.com/nICEnnnnnnnLee/BilibiliDown/wiki/How-to-log)

```
请在发表issue前进行预览，将影响排版的内容放到这里
```

**Comment by freedom-323** [comment]
DRM嘛
