### ISSUE TITLE
NSInvalidArgumentException

### ISSUE THREAD

**Issue by JimmyKent** [nICEnnnnnnnLee/BilibiliDown#148]
17款mac，intel芯片的，配置了ffmepg之后，报这个错误
正在获取验证AuthKey以生成二维码...
authKey: 26c9e5cea982da37c2059b53666716c4
正在生成二维码图片Frame
MJTitleBar-init/63 : 3
二维码图片已生成
2023-05-26 11:26:54.448 java[34435:415453] +[AWTView keyboardInputSourceChanged:]: unrecognized selector sent to class 0x10e1ca3e0
2023-05-26 11:26:54.450 java[34435:415453] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[AWTView keyboardInputSourceChanged:]: unrecognized selector sent to class 0x10e1ca3e0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff2055683b __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff2028ed92 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff205d92a5 __CFExceptionProem + 0
	3   CoreFoundation                      0x00007fff204be8cb ___forwarding___ + 1448
	4   CoreFoundation                      0x00007fff204be298 _CF_forwarding_prep_0 + 120
	5   CoreFoundation                      0x00007fff204d20cd __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	6   CoreFoundation                      0x00007fff2056db1c ___CFXRegistrationPost_block_invoke + 49
	7   CoreFoundation                      0x00007fff2056da9a _CFXRegistrationPost + 454
	8   CoreFoundation                      0x00007fff204a334e _CFXNotificationPost + 736
	9   Foundation                          0x00007fff21213bb8 -[NSNotificationCenter postNotificationName:object:userInfo:] + 59
	10  AppKit                              0x00007fff2308ac2b __NSSelectedKeyboardInputSourcesChangedNotification + 58
	11  CoreFoundation                      0x00007fff204d20cd __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	12  CoreFoundation                      0x00007fff2056db1c ___CFXRegistrationPost_block_invoke + 49
	13  libdispatch.dylib                   0x00007fff20238623 _dispatch_call_block_and_release + 12
	14  libdispatch.dylib                   0x00007fff20239806 _dispatch_client_callout + 8
	15  libdispatch.dylib                   0x00007fff20245b4f _dispatch_main_queue_callback_4CF + 940
	16  CoreFoundation                      0x00007fff205195a8 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	17  CoreFoundation                      0x00007fff204db7a2 __CFRunLoopRun + 2755
	18  CoreFoundation                      0x00007fff204da61c CFRunLoopRunSpecific + 563
	19  HIToolbox                           0x00007fff28720a83 RunCurrentEventLoopInMode + 292
	20  HIToolbox                           0x00007fff287207e5 ReceiveNextEventCommon + 587
	21  HIToolbox                           0x00007fff28720583 _BlockUntilNextEventMatchingListInModeWithFilter + 70
	22  AppKit                              0x00007fff22ce2172 _DPSNextEvent + 864
	23  AppKit                              0x00007fff22ce0945 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1364
	24  libosxapp.dylib                     0x0000000102fd391e -[NSApplicationAWT nextEventMatchingMask:untilDate:inMode:dequeue:] + 121
	25  AppKit                              0x00007fff22cd2c69 -[NSApplication run] + 586
	26  libosxapp.dylib                     0x0000000102fd3763 +[NSApplicationAWT runAWTLoopWithApp:] + 222
	27  libawt_lwawt.dylib                  0x000000010e190141 +[AWTStarter starter:headless:] + 834
	28  JavaNativeFoundation                0x00007fff6ea6e77f +[JNFRunLoop _performCopiedBlock:] + 15
	29  Foundation                          0x00007fff2128ab81 __NSThreadPerformPerform + 204
	30  CoreFoundation                      0x00007fff204dc94c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	31  CoreFoundation                      0x00007fff204dc8b4 __CFRunLoopDoSource0 + 180
	32  CoreFoundation                      0x00007fff204dc634 __CFRunLoopDoSources0 + 242
	33  CoreFoundation                      0x00007fff204db05c __CFRunLoopRun + 893
	34  CoreFoundation                      0x00007fff204da61c CFRunLoopRunSpecific + 563
	35  libjli.dylib                        0x0000000102e5a5f6 CreateExecutionEnvironment + 399
	36  libjli.dylib                        0x0000000102e56787 JLI_Launch + 1315
	37  java                                0x0000000102e40b6f main + 367
	38  libdyld.dylib                       0x00007fff203fef3d start + 1
)
libc++abi: terminating with uncaught exception of type NSException
/Users/jinguochong/Downloads/BilibiliDown.v6.25.win_x64_jre11.release/Double-Click-to-Run-for-Mac.command: line 6: 34435 Abort trap: 6           java -Dfile.encoding=utf-8 -Dhttps.protocols=TLSv1.2 -jar launch.jar

**Comment by nICEnnnnnnnLee** [comment]
看上去像是jdk的问题，似乎CMD+ALT+Space可以稳定触发
```
https://github.com/oracle/graal/issues/4026
https://github.com/apache/jmeter/issues/5533
```
