### ISSUE TITLE
Mac平台下无法识别INeedBiliAV.jar同级目录下的ffmpeg

### ISSUE THREAD

**Issue by CZFlyingEagle** [nICEnnnnnnnLee/BilibiliDown#15]
视频下载完成后无法正常合并，提示没有ffmpeg环境

**Comment by CZFlyingEagle** [comment]
看了一下源码，感觉好像没什么问题.
在终端直接输入ffmpeg -version是有相应的，但是不晓得为什么在这个包里面不起作用导致音视频无法正常合并

**Comment by nICEnnnnnnnLee** [comment]
> 在终端直接输入ffmpeg -version是有响应的  

请问这个响应是切换到**INeedBiliAV.jar**所在目录下，还是默认的目录:flushed:

**Comment by nICEnnnnnnnLee** [comment]
另外，在这个问题没有解决的情况下，可以先试试下载FLV格式的。
+ 将`app.config`里面修改设置`bilibili.format = 1`

**Comment by nICEnnnnnnnLee** [comment]
假设**INeedBiliAV.jar**所在目录为`/home/workspace/BilibiliDown`。
* **问题1** 请问各目录ffmpeg -version命令行的运行情况
     + 主目录
     ```
    cd ~
    ffmpeg -version
    ```

    + 程序目录
    ```
    cd /home/workspace/BilibiliDown
    ffmpeg -version
    ```
* **问题2** 请问您是如何调用程序的？
    + 情况A
    ```
    cd /home/workspace/BilibiliDown
    javaw -Dfile.encoding=utf-8 -jar INeedBiliAV.jar
    ```
    + 情况B
    ```
    javaw -Dfile.encoding=utf-8 -jar /home/workspace/BilibiliDown/INeedBiliAV.jar
    ```

**Comment by CZFlyingEagle** [comment]
问题1:在主目录和程序目录下，执行指令均有正常相应.

问题2:使用的是第二种启动方式


iPhoneから送信

**Comment by nICEnnnnnnnLee** [comment]
+ Mac下Runtime执行调用的仅仅只是系统的/bin/下的指令，似乎设置的path不会生效。
+ 请帮忙测试一下[V4.1](https://github.com/nICEnnnnnnnLee/BilibiliDown/releases/tag/V4.1)看看效果:flushed:
    + 在`config/app.config`里面指定好`bilibili.ffmpegPath`，然后再运行
    + 举个例子：
    ```
    bilibili.ffmpegPath = D:\Workspace\javaweb-springboot\BilibiliDown\ffmpeg.exe
    ```

**Comment by CZFlyingEagle** [comment]
V4.1 在Mac上经测试可以正常工作【包括合并MP4和合并长flv视频】，只需要在启动之前定义一下app.config里面的路径就可以了. 非常感谢！
类似的在Linux上应该也可以正常工作了.
【P.S.这Debug速度真的神了……】
