### ISSUE TITLE
可以加下那个杜比视界的清晰度下载

### ISSUE THREAD

**Issue by ghost** [nICEnnnnnnnLee/BilibiliDown#152]
我最近发现下载杜比视界好像用不了
顺便提一下，可以加入读取剪贴板中匹配的视频链接功能吗

**Comment by nICEnnnnnnnLee** [comment]
> 我最近发现下载杜比视界好像用不了 

+ 你是B站大会员吗？
+ 你知道怎样使用本程序下载杜比视界吗，请罗列你的相关配置？
+ 你在下载前测试过配置说明提及的BV号吗？如果可以，那么又是下载哪个BV号的杜比视界失败的呢？

> 顺便提一下，可以加入读取剪贴板中匹配的视频链接功能吗？

#25

<hr>

你以后能够一个问题只专注于一件事吗？
