### ISSUE TITLE
[Feature] 期望能添加新功能实时备份

### ISSUE THREAD

**Issue by swRains** [nICEnnnnnnnLee/BilibiliDown#163]
期望能够做个实时嗅探并下载收藏夹，这样一加入收藏夹就可以备份下载下来了。数据库存一下已下载的视频和分P，有更新就补充下载合集。取消收藏最好不要删除文件，数据库上打个标记，管理界面做个单个或批量清理按钮。
封装成docker放nas上，做个简易的web管理，有效防止视频失效。

找了很久这样的软件，都是手动搞的，期望up能考虑下这个需求，我看B站上还是有很多人有这个需求的，加油！

**Comment by nICEnnnnnnnLee** [comment]
我的理解是，这是个适用于headless system的需求。对于一个基于Swing的GUI程序来说，这个问题实在是太奇怪了。    

建议去找找基于Web的项目；或者找相关CLI应用，然后使用脚本周期调用。
