### ISSUE TITLE
下载问题

### ISSUE THREAD

**Issue by davidqqd** [nICEnnnnnnnLee/BilibiliDown#164]
某个视频误下载了一次480P清晰度的，则无法再次下载1080P高清晰度的，系统提示“您已经下载过 XXX ”

**Comment by nICEnnnnnnnLee** [comment]
[帮助文档](https://nicennnnnnnlee.github.io/BilibiliDown/guide/frequently-asked/why-always-prompt)  
[备用帮助文档](https://bili.nicelee.top/BilibiliDown/guide/frequently-asked/why-always-prompt)
