### ISSUE TITLE
首次运行“run-UI.bat”时报错

### ISSUE THREAD

**Issue by zfang1995** [nICEnnnnnnnLee/BilibiliDown#17]
报错信息：当前没有ffmpeg环境.....

软件运行环境：windows10 x64 17134

**Comment by hsj-xiaokang** [comment]
吧FFmpeg.exe放在同run-UI.bat文件夹即可

**Comment by hsj-xiaokang** [comment]
> 报错信息：当前没有ffmpeg环境.....
> 
> 软件运行环境：windows10 x64 17134

把ffmpeg.exe放在同run-UI.bat文件夹下即可

**Comment by xihadandan** [comment]
下载异常
