### ISSUE TITLE
希望贡献代码

### ISSUE THREAD

**Issue by codeboysky** [nICEnnnnnnnLee/BilibiliDown#171]
作者，你好
感谢你开发的项目，我觉得非常好用，但是在使用中我想增加一个定时一键下载功能和消息推送功能，方便离线收集自己喜欢的视频，该代码我已开发完毕，可以合并到该项目中吗？

**Comment by nICEnnnnnnnLee** [comment]
对于不是那么紧要的新功能，如果对现有的东西侵入不大，只需改动少量已有代码、如果没有引入其它依赖，或过分地增加程序最终的体积、如果后续维护比较简单，那么可以考虑接受。

**Comment by codeboysky** [comment]
作者，你好
我已经提交了一个PR，可以查看以下。
考虑增加这个功能是因为有一些学习视频，在App上看完后想下载到电脑里进行保存，供后续的学习和研究使用，使用定时下载这个功能就很好的可以实现这个想法，把想要下载的资料保存到对应的收藏夹即可。
之前沟通中也提到了，对于大部分的用户确实可能用不上，因为他们没有24小时开机的习惯，但是对于有NAS的小伙伴确实很好用。但是你也提到了使用NAS存在无法登录问题，这个问题我也考虑到了，可以通过vnc将应用画面投射到浏览器进行访问，从而变相实现该应用的网页版。

**Comment by codeboysky** [comment]
其实我在选择这个项目前我也查看了其他的一些类似项目，但是感觉该项目做的是最好的了，功能齐全还非常强大，所以也非常方便后续再添加一些功能。

我想添加这个功能主要是有几个诉求
1. 现在我经常是使用App看B站，因为有NAS，看好想下载的内容就不想每次都打开电脑下载了后再手动传到NAS上，这样直接在App上收藏到指定收藏夹就可以实现了
2. 这第二点其实也跟第一点有联系，因为视频中讲的内容非常细致了，在经过后期学习和整理后，可以直接将下载到NAS中的视频，添加到我个人的Obsidian笔记中，方便后面再回顾知识点
3. 经常在B站上看到不错的学习资料，想在后面有时间的时候学习学习，但是因为各种原因吧，后面可能就下架了，通过我这个方案也可以直接保存下来了

**Comment by specked2527** [comment]
> 其实我在选择这个项目前我也查看了其他的一些类似项目，但是感觉该项目做的是最好的了，功能齐全还非常强大，所以也非常方便后续再添加一些功能。
> 
> 我想添加这个功能主要是有几个诉求
> 
> 1. 现在我经常是使用App看B站，因为有NAS，看好想下载的内容就`不想每次都打开电脑下载了后再手动传到NAS上`，这样直接在App上收藏到指定收藏夹就可以实现了
> 2. 这第二点其实也跟第一点有联系，因为视频中讲的内容非常细致了，在经过后期学习和整理后，可以直接将下载到NAS中的视频，添加到我个人的Obsidian笔记中，方便后面再回顾知识点
> 3. 经常在B站上看到不错的学习资料，想在后面有时间的时候学习学习，但是因为各种原因吧，后面可能就下架了，通过我这个方案也可以直接保存下来了

`不想每次都打开电脑下载了后再手动传到NAS上`， 你是否再找 :sweat_smile: https://github.com/nilaoda/BBDown 你可以手机ssh连接电脑/NAS（linux）输入命令下载（批量），

**Comment by codeboysky** [comment]
> > 其实我在选择这个项目前我也查看了其他的一些类似项目，但是感觉该项目做的是最好的了，功能齐全还非常强大，所以也非常方便后续再添加一些功能。
> > 我想添加这个功能主要是有几个诉求
> > 
> > 1. 现在我经常是使用App看B站，因为有NAS，看好想下载的内容就`不想每次都打开电脑下载了后再手动传到NAS上`，这样直接在App上收藏到指定收藏夹就可以实现了
> > 2. 这第二点其实也跟第一点有联系，因为视频中讲的内容非常细致了，在经过后期学习和整理后，可以直接将下载到NAS中的视频，添加到我个人的Obsidian笔记中，方便后面再回顾知识点
> > 3. 经常在B站上看到不错的学习资料，想在后面有时间的时候学习学习，但是因为各种原因吧，后面可能就下架了，通过我这个方案也可以直接保存下来了
> 
> `不想每次都打开电脑下载了后再手动传到NAS上`， 你是否再找 😅 https://github.com/nilaoda/BBDown 你可以手机ssh连接电脑/NAS（linux）输入命令下载（批量），
> 
> FreeFileSync可以帮你同步文件 https://freefilesync.org/

说实在的，你推荐的这个也是很棒的工具👍，但是我还是更喜欢在[BilibiliDown](https://github.com/nICEnnnnnnnLee/BilibiliDown)上添加自动下载功能，原因如下
1. 不需要手动去进行下载，只需要把App上喜欢的内容收藏起来就可以自动下载了，这样对不同客户端兼容性最好，并且非常简单不需要有太多开发基础
2. 可以通过多种形式查看下载情况，比如在应用中查看，也可以通过接收推送消息来获取
