### ISSUE TITLE
希望支持使用SESSDATA登录

### ISSUE THREAD

**Issue by MC-XiaoHei** [nICEnnnnnnnLee/BilibiliDown#175]
我已经确认

- [x]  使用的当前版本为最新版本

- [x]  issue区没有类似的情况（有的话请直接去该问题讨论）

问题描述
希望支持使用SESSDATA登录
有时没有移动端，可以通过SESSDATA登录下载

**Comment by nICEnnnnnnnLee** [comment]
+ 理论上，使用用户名密码登录，可以不需要移动端

+ Cookie相关的东西保存在`config`文件夹下的`cookies.config`、`fingerprint.config`，浏览器UA设置可以在配置页搜`bilibili.userAgent.pc`。其中`refresh_token`可以从localStorage里的`ac_time_value`获取。  
    + [cookies.config](https://nicennnnnnnlee.github.io/BilibiliDown/config/cookies)
    + [fingerprint.config](https://nicennnnnnnlee.github.io/BilibiliDown/config/fingerprint)

**Comment by MC-XiaoHei** [comment]
好的，感谢解答
