### ISSUE TITLE
软件无法自适应高分辨率, 当分辨率过高, 会出现过小的情况

### ISSUE THREAD

**Issue by NoString** [nICEnnnnnnnLee/BilibiliDown#176]
**我已经确认**
- 使用的当前版本为最新版本: ✔
- 使用最新的CI版本仍然存在该问题[CI传送门](https://github.com/nICEnnnnnnnLee/BilibiliDown/actions/workflows/pre-release-artifacts.yml): 没用, 因为并不是某些功能无法使用
- issue区没有类似的情况（有的话请直接去该问题讨论）:尝试搜索关键词"分辨率", 无相关结果

**问题描述**
笔记本分辨率为3200x2000, 15.6寸.   
~~看个设置要把头塞到电脑屏幕里, 谢谢UP,已经进入二次元了.~~
![picture](https://raw.githubusercontent.com/NoString/image/main/note/202312211117627.png)

**相关信息**
+ 当前系统(windows/linux等):Windwos
+ java版本: java version "1.8.0_111"
+ 相关链接或者BV号: 非下载功能问题
+ 账号是否登录: 是
+ 在网页端观看是否存在问题: 是
+ 是否存在自定义parsers: 否
+ 相关log
  + 如何抓log请参考[Wiki-How to log](https://github.com/nICEnnnnnnnLee/BilibiliDown/wiki/How-to-log)

```
请在发表issue前进行预览，将影响排版的内容放到这里
```

**Comment by nICEnnnnnnnLee** [comment]
这个问题需要升级Java版本来解决，Java 8并不支持自适应分辨率。  
如果升级后仍不满意，还想再调整大小，可以参考 #133
