### ISSUE TITLE
下载异常

### ISSUE THREAD

**Issue by nICEnnnnnnnLee** [nICEnnnnnnnLee/BilibiliDown#18]
下载异常
![image](https://user-images.githubusercontent.com/15681750/68570535-e95f4b80-049b-11ea-92d9-94423fa87e6d.png)

_Originally posted by @xihadandan in https://github.com/nICEnnnnnnnLee/BilibiliDown/issues/9#issuecomment-552333098_

**Comment by nICEnnnnnnnLee** [comment]
请确认一下是否是网络问题，或者提供更详细的log以及相关信息。  
我本地测试下载` av71415770 p1 清晰480p`没发现啥问题。

**Comment by xihadandan** [comment]
不好意思！是网络问题！可关闭此issues
