### ISSUE TITLE
建议增加设置背景的功能（实在是首页背景个人感觉太乱了）

### ISSUE THREAD

**Issue by QuanPengWang** [nICEnnnnnnnLee/BilibiliDown#181]
如题，目前使用得应该是最新版本（6.29）
感觉首页的背景实在太乱了，而且在设置中没有明显的修改地方。
建议能不能增加一个修改的地方
或者直接首页背景是全白之类的纯色也是好一点的
十分感谢。

**Comment by kawuwa** [comment]
附议

**Comment by chensimmons** [comment]
工具是好的，但这个背景实在难绷，真的太丑了

**Comment by nICEnnnnnnnLee** [comment]
[自定义背景图](https://nicennnnnnnlee.github.io/BilibiliDown/guide/advanced/custom-background-img)
