### ISSUE TITLE
一键批量下载后，某些文件并没有自动标题，只有BV码，这该怎么办？

### ISSUE THREAD

**Issue by 4965898** [nICEnnnnnnnLee/BilibiliDown#185]
**我已经确认**
- 使用的当前版本为最新版本v6.3

**问题描述**
一键批量下载后，某些文件并没有自动标题，只有BV码，这该怎么办？

**相关信息**
![QQ截图20240410190008](https://github.com/nICEnnnnnnnLee/BilibiliDown/assets/75034137/7765ea3b-e29a-4ced-891c-7a393a6926c3)

```

**Comment by nICEnnnnnnnLee** [comment]
+ 文件没有完成重命名，大概率是因为目的地有相同名称的文件。你需要调整一下配置`自定义文件名`，比如将BV号加进去。

+ 调整配置，使程序可以下载`已下载的视频`

+ 在原来的一键配置的基础上，将原来的`download.condition`去除，参考以下进行修改。
```
[favorite:收藏夹1]
stop.condition = page:20

download.condition = bv:BV1Yf4y1K7Gs
download.condition = bv:BV1Ag411U7nf
download.condition = bv:BV1pY411E7Y9
...
download.condition = bv:BV1CB4y1g7sF

[url:链接1]
stop.condition = page:20

download.condition = bv:BV1Yf4y1K7Gs
download.condition = bv:BV1Ag411U7nf
download.condition = bv:BV1pY411E7Y9
...
download.condition = bv:BV1CB4y1g7sF
```

**Comment by 4965898** [comment]
好的，我试试，非常感谢
