### ISSUE TITLE
下载专辑重命名失败

### ISSUE THREAD

**Issue by Zarves76** [nICEnnnnnnnLee/BilibiliDown#189]
专辑下载完成后文件名是专辑名后加序列号，而不是每个文件自身的文件名。
比如
https://www.bilibili.com/video/BV14t411D7v4?p=14&vd_source=180182617b17874505042925d21f2ca5

这个专辑下载后文件名是 **Physics Videos 物理视频【127集 英文字幕】p01-80** 这种形式，而不是

![Screenshot 2024-05-04 221737](https://github.com/nICEnnnnnnnLee/BilibiliDown/assets/46805399/2f04e28e-f92c-4bfe-a34f-d82a55401cdf)
这种单独的文件名。

请问应该如何解决。谢谢

**Comment by nICEnnnnnnnLee** [comment]
各分p视频的标题可用`clipTitle`表示。你可以按需自定义文件名。

http://nicennnnnnnlee.github.io/BilibiliDown/guide/advanced/custom-file-name#cliptitle

**Comment by Zarves76** [comment]
解决了，谢谢
