### ISSUE TITLE
请问批量下载功能是否可以进一步完善

### ISSUE THREAD

**Issue by kukudemajia** [nICEnnnnnnnLee/BilibiliDown#19]
首先要感谢大佬分享如此好用的工具
虽然小星星不多，但是确实实用
现在遇到的问题就是批量下载有点麻烦，也可能是我没有完全掌握
比如这个https://space.bilibili.com/128509821/channel/detail?cid=36681
能否有类似爬虫一样的可以自动抓取URL然后做下载队列呢？
就这个我要按十几次下一页才好像才能下载完全
有大部分没有转换成功，还是flv

**Comment by nICEnnnnnnnLee** [comment]
> 就这个我要按十几次下一页才好像才能下载完全

+ 分页大小可以在`config/app.config`中修改`bilibili.pageSize = 5`
+ 默认分页大小为5，可以根据需要适当调整，比如20。
+ 不建议设置得太大，因为会为每个av查询可用清晰度，这会产生(1~2)*pageSize 个网络请求
+ 还有一个已知问题，如果channel中存在已失效视频，那么该分页中已失效视频之后的视频信息将全部丢失
<hr/>

+ 如果不考虑内容，目的是**全部**下载，可以直接在主页一直点下一页，等页面加载完毕后，  
    + `菜单栏->配置 ->下载策略-> 全部`，  
    + `菜单栏->操作 -> 批量下载Tab页`
而不必每个页面都进去点一遍

**Comment by nICEnnnnnnnLee** [comment]
>
> 有大部分没有转换成功，还是flv

+ 一般来说，我会优先去解析m4s的链接，然后音视频合成mp4。
+ 出现这种情况，大概率是因为B站对应的av只有flv源，没有m4s。考虑到flv也是一种常见的多媒体格式，能够被大多数播放器解析，也就没有处理

**Comment by kukudemajia** [comment]
> > 就这个我要按十几次下一页才好像才能下载完全
> 
> * 分页大小可以在`config/app.config`中修改`bilibili.pageSize = 5`
> * 默认分页大小为5，可以根据需要适当调整，比如20。
> * 不建议设置得太大，因为会为每个av查询可用清晰度，这会产生(1~2)*pageSize 个网络请求
> * 还有一个已知问题，如果channel中存在已失效视频，那么该分页中已失效视频之后的视频信息将全部丢失(收藏夹用得最多，冇问题。这个将在下个版本解决）
> 
> * 如果不考虑内容，目的是**全部**下载，可以直接在主页一直点下一页，等页面加载完毕后，
>   
>   * `菜单栏->配置 ->下载策略-> 全部`，
>   * `菜单栏->操作 -> 批量下载Tab页`
>     而不必每个页面都进去点一遍

非常感谢

**Comment by kukudemajia** [comment]
> > 有大部分没有转换成功，还是flv
> 
> * 一般来说，我会优先去解析m4s的链接，然后音视频合成mp4。
> * 出现这种情况，大概率是因为B站对应的av只有flv源，没有m4s。考虑到flv也是一种常见的多媒体格式，能够被大多数播放器解析，也就没有处理

好的，如果能够自动转成MP4最好，不过就算没有转换也完全可以接受
