### ISSUE TITLE
专辑下载不完整

### ISSUE THREAD

**Issue by Zarves76** [nICEnnnnnnnLee/BilibiliDown#190]
比如下面这个专辑 https://www.bilibili.com/video/BV1Vx411j7HK/?vd_source=180182617b17874505042925d21f2ca5

有191的视频，解析也解析了191个，但是下载的时候到103个就停止了，后面104-191就没有出现在下载列表里。请问如何解决

![Screenshot 2024-05-05 140349](https://github.com/nICEnnnnnnnLee/BilibiliDown/assets/46805399/e8166504-00e7-4d5b-ac48-9898489bbe8e)

**Comment by nICEnnnnnnnLee** [comment]
目测是被风控了。请按照issue模板提供包括log在内的更详细的信息

**Comment by Zarves76** [comment]
谢谢回复。

我暂时解决了这个问题。办法就是在下载页面完成后再点“批量下载”，点取消后又可以接着下一批，重复操作就可以下载完全部专辑。
