### ISSUE TITLE
无法登录，解析链接非常慢

### ISSUE THREAD

**Issue by shaoscotti** [nICEnnnnnnnLee/BilibiliDown#191]
**我已经确认**
- 使用的当前版本为最新版本
- 使用最新的CI版本仍然存在该问题[CI传送门](https://github.com/nICEnnnnnnnLee/BilibiliDown/actions/workflows/pre-release-artifacts.yml)
- issue区没有类似的情况（有的话请直接去该问题讨论）

**问题描述**
无法登录，二维码，账户名，短信全都不行。解析视频链接非常慢。软件几乎不可用

**相关信息**
+win10 22h2
+ java版本 openjdk 21.0.2 2024-01-16 LTS
+ 相关链接或者BV号
+ 账号是否登录
+ 在网页端观看是否存在问题
+ 是否存在自定义parsers
+ 相关log
  + 如何抓log请参考[Wiki-How to log](https://github.com/nICEnnnnnnnLee/BilibiliDown/wiki/How-to-log)

```
请在发表issue前进行预览，将影响排版的内容放到这里
```

**Comment by nICEnnnnnnnLee** [comment]
> 
> 解析视频链接非常慢。软件几乎不可用

我这里登录没问题。这种无法复现的情况请提供log。  

> 
> 解析视频链接非常慢

请详细描述，并附上log。比如：
解析链接 `https://www.bilibili.com/video/BVxxxxxxx/ `花了我 xx 秒。
后附log。

**Comment by shaoscotti** [comment]
6.31版本可用，6.30版本还是登录不上，解析视频下载界面就加载不出来



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月8日(周三) 晚上8:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [nICEnnnnnnnLee/BilibiliDown] 无法登录，解析链接非常慢 (Issue #191)




  
解析视频链接非常慢。软件几乎不可用
  
我这里登录没问题。这种无法复现的情况请提供log。
  
解析视频链接非常慢
  
请详细描述，并附上log。比如：
 解析链接 https://www.bilibili.com/video/BVxxxxxxx/ 花了我 xx 秒。
 后附log。
