### ISSUE TITLE
可以解析单个视频链接，但是无法解析up所有的视频连接

### ISSUE THREAD

**Issue by 1027690140** [nICEnnnnnnnLee/BilibiliDown#192]
**问题描述**

例如：视频 https://www.bilibili.com/video/BV1TC411E71B/    可以解析
但是  该up   https://space.bilibili.com/1423777208  无法解析   显示无效预览图

![image](https://github.com/nICEnnnnnnnLee/BilibiliDown/assets/60860963/ff9abe11-f8c0-48f5-b3f1-03b018f785bd)

**Comment by changsonghuai** [comment]
同样的问题 可能是b站改接口了

**Comment by siegtoule** [comment]
遇到同样的问题
