### ISSUE TITLE
下载的弹幕变成乱码

### ISSUE THREAD

**Issue by TeslaCoil-X** [nICEnnnnnnnLee/BilibiliDown#197]
**我已经确认**
- 使用的当前版本为最新版本：v6.31
- 使用最新的CI版本仍然存在该问题：v6.31的版本号比CI版本还新
- issue区没有类似的情况

**问题描述**
使用运行【Create-Shortcut-on-Desktop-for-Win.vbs】后产生的【Bili 下载器】桌面快捷方式运行程序后下载的ASS格式弹幕都是乱码，另存了很多种编码格式都没有恢复正常；但是如果使用【Double-Click-to-Run-for-Win-debug.bat】这个批处理文件运行程序，下载下来的弹幕就都是正常的。这是什么奇怪的问题，观测即坍缩吗？？😂🤣

**相关信息**
+ 当前系统：Windows11 23H2
+ java版本：v6.31自带Java环境
+ 相关链接或者BV号：https://space.bilibili.com/21416270/favlist?fid=947222670
+ 账号是否登录：已登录
+ 在网页端观看是否存在问题：无问题
+ 是否存在自定义parsers
+ 相关log：[log.txt](https://github.com/nICEnnnnnnnLee/BilibiliDown/files/15362518/log.txt)

**Comment by nICEnnnnnnnLee** [comment]
这是由于默认编码不是utf8而引起的。


+ 你可以修改 `Double-Click-to-Run-for-Win-debug.bat` 文件的编码为 `utf-8`  

  ```cmd
  start javaw -Dfile.encoding=utf-8 -Dhttps.protocols=TLSv1.2 -jar launch.jar 
  ```

   https://github.com/nICEnnnnnnnLee/BilibiliDown/blob/d0ae71932de003809eb7e5136f5db490be67bc4b/release/Double-Click-to-Run-for-Win.bat#L6


+ 或者，你可以下载GitHub action编译的最新版本  
  + https://github.com/nICEnnnnnnnLee/BilibiliDown/actions/runs/9154198211
