### ISSUE TITLE
很奇怪的逻辑

### ISSUE THREAD

**Issue by reov** [nICEnnnnnnnLee/BilibiliDown#2]
第一个为什么不能右键粘贴呢，非要手打av号，第二个收藏列表怎么批量下载，看链接是mlXXXX

**Comment by nICEnnnnnnnLee** [comment]
1. 平时Ctrl + C/V 用惯了，没有考虑到右键粘贴这个功能，**这个可以添加进去**  
2. 目前不支持批量下载。:flushed:  
    + 对于收藏列表，在浏览器里面打开个人中心，进入收藏夹，复制地址栏的链接，然后和其它操作一样，会弹开收藏夹里的av标签页。
    + 目前支持的收藏夹链接长这样<https://space.bilibili.com/123/favlist?fid=1234&ftype=create>
    像这种链接漏了<https://www.bilibili.com/medialist/detail/ml1234?type=2>，**这个可以添加进去** 
    像mlXXX, fidXXX这种参数不知道是不是唯一的，**ml可以考虑** 
    + 如果链接解析失败，可以登录再进行尝试
    + 浏览器里面每页max视频数为30， 为了防止弹出的页面过多，在我这里设的是5。

**Comment by nICEnnnnnnnLee** [comment]
> 
> 
>     1. 平时Ctrl + C/V 用惯了，没有考虑到右键粘贴这个功能，**这个可以添加进去**
> 
>     2. 目前不支持批量下载。😳
>        
>        * 对于收藏列表，在浏览器里面打开个人中心，进入收藏夹，复制地址栏的链接，然后和其它操作一样，会弹开收藏夹里的av标签页。
>        * 目前支持的收藏夹链接长这样https://space.bilibili.com/123/favlist?fid=1234&ftype=create
>          像这种链接漏了https://www.bilibili.com/medialist/detail/ml1234?type=2，**这个可以添加进去**
>          像mlXXX, fidXXX这种参数不知道是不是唯一的，**ml可以考虑**
>        * 如果链接解析失败，可以登录再进行尝试
>        * 浏览器里面每页max视频数为30， 为了防止弹出的页面过多，在我这里设的是5。要变更页数直接在链接后面加上` p=XXX`

加粗的在[V2.8](https://github.com/nICEnnnnnnnLee/BilibiliDown/releases/tag/V2.8)实现了:flushed:

**Comment by nICEnnnnnnnLee** [comment]
批量下载的**Feature**在[V2.9](https://github.com/nICEnnnnnnnLee/BilibiliDown/releases/tag/V2.9)应该全部实现了

* 根据策略下载所有打开标签页的(全部/第一个)视频  
![](https://raw.githubusercontent.com/nICEnnnnnnnLee/BilibiliDown/master/release/prelook/downloadAllTab.png)  
* 对于多p的AV， 根据清晰度优先级批量下载  
![](https://raw.githubusercontent.com/nICEnnnnnnnLee/BilibiliDown/master/release/prelook/downloadSingleTab.png)
