### ISSUE TITLE
readme 能添加下 项目的get start 吗

### ISSUE THREAD

**Issue by chen1zee** [nICEnnnnnnnLee/BilibiliDown#20]
readme 能添加下 项目的get start 吗
首先我是 对 java 不太懂的， 主要搞 go c js
用 idea  jdk 13
![捕获](https://user-images.githubusercontent.com/18671317/71637558-d89faa80-2c80-11ea-85d3-ef0b91c13368.PNG)

打开项目之后 路径 包路径 没有 映射，希望能简单的加个 开发配置，让我这菜鸡能 参考下 大佬的代码。

**Comment by nICEnnnnnnnLee** [comment]
![导入](https://user-images.githubusercontent.com/19970934/71639638-0acaff80-2cb5-11ea-8e1e-27b815c81f97.png)

**Comment by nICEnnnnnnnLee** [comment]
junit和jdk应该需要再改一下配置

**Comment by chen1zee** [comment]
可以嘞，谢谢
