### ISSUE TITLE
软件功能看起来很强大，但是

### ISSUE THREAD

**Issue by imdvpt** [nICEnnnnnnnLee/BilibiliDown#201]
![屏幕截图 2024-06-20 145207](https://github.com/nICEnnnnnnnLee/BilibiliDown/assets/103763729/74fb7ff6-6671-421b-bb58-0fef5d60e491)
这个界面是认真的吗？当我首次打开这个软件还以为是奔溃了，后来还重复打开了几次。。。
我的天啊，花里花哨的，第一次不仔细看我都看不到输入框及用户登录。。我相信作者应该是个技术流吧
还有这个配置和下载 ，甚至找不到怎么去点下载

吐槽完毕，建议学习一下主流的下载软件配置吧，比如迅雷或qbittorrent。。按用户习惯去做以减少学习成本

**Comment by nICEnnnnnnnLee** [comment]
我写了些话，但预计可能会引发对抗性的言论，就把它删了，只留下这句表明态度。  

总之，你说的看起来很有道理，但是...我拒绝

**Comment by vanjune** [comment]
他有啥道理，虽然目前简约风是主流，虽然我个人也满喜欢简约的，但迅雷无论如何也说不上简约吧

经常看B站的用户都知道，目前这个界面，就真的很B站，灵魂复刻了属于是，支持n大！
