### ISSUE TITLE
你好，能否增加一个每读取5个下载5个的选项？

### ISSUE THREAD

**Issue by asdasdasdzxcgreter** [nICEnnnnnnnLee/BilibiliDown#202]
有的时候连续下载多个UP作品，有可能是几千个的时候，网速不够快，后面的还没下载完，就变成红色的了。
能不能设置成读取10个下载10个，下载完再继续读取后面的？
谢谢大哥了。

**Comment by nICEnnnnnnnLee** [comment]
逻辑上，先要查询能否获取指定清晰度的视频，判断是否要进行任务，再生成下载任务放进线程池的。这个设计不打算改了。    

下载任务过多，导致一段时间后下载链接过期，在最开始没考虑过这种场景。
这个问题最初在#120 提到过，当时给出的解决方案是下载失败后重新尝试获取链接(需要修改配置)。   
姑且认为在看完帮助文档使用了解决方案后仍然存在问题。  

想了想，当前版本有两个地方不妥：
+ 明知道一段时间后，下载链接必然失败，仍然要先尝试下载，失败后再去获取链接
+ 失败后重新下载的任务添加到了队列的末尾，必须要把之前队列里的任务先过一遍  
  
考虑极端情况，以上可能导致短时间内频繁403然后被ban；或者在一轮任务后重新获取的下载链接又失效了(任务巨多且配置了时间间隔的情况下)

为此，在下个版本：  
+ 队列的下载任务取出后，先判断下载链接的存在时间是否超过阈值，然后再进行下载  
+ 失败后重新下载的任务在队列里的优先级更高

**Comment by asdasdasdzxcgreter** [comment]
谢谢大哥。那我减少下载数量也能解决的，就是要经常再次下载，也没关系。谢谢大哥软件！
