### ISSUE TITLE
能否增加特性：输入多个地址用空格隔开，打开相应的tab页

### ISSUE THREAD

**Issue by vanjune** [nICEnnnnnnnLee/BilibiliDown#203]
**我已经确认**
- 使用的当前版本为最新版本
- 使用最新的CI版本仍然存在该问题[CI传送门](https://github.com/nICEnnnnnnnLee/BilibiliDown/actions/workflows/pre-release-artifacts.yml)
- issue区没有类似的情况（有的话请直接去该问题讨论）

**问题描述**
以前的版本支持输入多个地址，用空格隔开，现在不行了，是取消该功能了吗，非常好用，求恢复

**相关信息**
+ 当前系统windows
+ java版本 未知
+ 相关链接或者BV号 无
+ 账号是否登录 已登录
+ 在网页端观看是否存在问题 没问题
+ 是否存在自定义parsers 无
+ 相关log

**Comment by nICEnnnnnnnLee** [comment]
> 
>  以前的版本支持输入多个地址，用空格隔开，现在不行了

以前分页查询的链接可以选择将结果放在一个Tab页，或者分别弹出Tab页。  
后来感觉有点鸡肋（可能导致大量并发请求、Tab页过多导致OOM），就取消了后者。    

在这个功能没有取消之前，如果`输入多个地址用空格隔开`，且第一个地址是`UP主所有视频`类型的，确实可以实现该效果。  
但这个结果，怎么说，其实是不符合预期的。这个功能没有正式支持过。


----
> 
>  求恢复

+ 这个功能和`搜索UP主所有视频`的链接类型可能冲突。    
比如搜索关键词含有空格的情况：
    一般从网页地址栏抠的没事，但也有未经url encode的情况，甚至这样更加方便理解与修改。e.g.  
    ```
    https://space.bilibili.com/336399506/search/video?keyword=SCP%20%E8%A1%A5%E6%A1%A3
    https://space.bilibili.com/336399506/search/video?keyword=SCP 补档
    ```
    需要注意的是，这样是不行的
    ```
    https://space.bilibili.com/336399506/search/video?keyword=SCP%20补档
    ```

+ 个人认为这样的需求还是挺少的，请具体描述一下你的使用场景，看看有没有其它方法替代。

  + 举个例子，使用场景`直接在程序首页的输入框拼接链接，链接内容不限`:
    + `Ctrl + C`地址，输入框末尾`Ctrl + V`，输入框末尾`Space空格`   
    + 重复步骤，直至所有地址输入完毕  
    + `Enter回车` 

  + 个人认为和下面这个差不多：
    + `Ctrl + C`地址，首页框`Ctrl + V`，`Enter回车`，
    + `Ctrl + C`地址，首页框`Ctrl + A`，`Ctrl + V`，`Enter回车`
    + 重复步骤，直至所有地址输入完毕

**Comment by vanjune** [comment]
我不知道咋滴就发现了这个特性，然后整理的需要保存的up主地址，现在列表可长了，大概如下：

野生CEO大宝			https://space.bilibili.com/430372013/
唐晓婷麻辣职场		https://space.bilibili.com/3494377859058000
-单位晋升			https://space.bilibili.com/1029508158?spm_id_from=333.337.0.0
-译论商业			https://space.bilibili.com/3546582116993464
...

然后，选中啊，按个热键autohotkey整理一下，出来一堆地址，用空格隔开的，切到你的软件下粘贴回车，真好用，更新后就不行了

恢复一下这个特性吧，求求了

**Comment by vanjune** [comment]
或者能不能增加一个特性，开个http server，接受post过来的url，打开相应的tab

**Comment by nICEnnnnnnnLee** [comment]
建议[通过配置一键下载 ](https://nicennnnnnnlee.github.io/BilibiliDown/guide/advanced/quick-batch-download)。  
详细的配置描述参考[batchDownload.config](https://nicennnnnnnlee.github.io/BilibiliDown/config/batchDownload)。

**Comment by vanjune** [comment]
主要是想下载指定up主的全部视频，走一键下载制定收藏夹不行吧

**Comment by nICEnnnnnnnLee** [comment]
下载收藏夹是很常见的场景，帮助文档用来举例理所当然。  

`通过配置一键下载`可以模拟下载程序支持解析的任何链接。
