### ISSUE TITLE
批量下载文件最多100？

### ISSUE THREAD

**Issue by chen12345chen** [nICEnnnnnnnLee/BilibiliDown#205]
我不确定是我没找到设置位置还是没有，我视频分200p，我批量下载只能下载到前100p

**Comment by nICEnnnnnnnLee** [comment]
请详细描述复现的操作、预期结果和实际结果

**Comment by chen12345chen** [comment]
> 请详细描述复现的操作、预期结果和实际结果

一个视频选集有分200P，我链接粘贴到软件后，选择批量下载。发现只下载了前100P，并且对应这个100数值我没有找到设置地点

**Comment by nICEnnnnnnnLee** [comment]
请给出具体链接

**Comment by chen12345chen** [comment]
https://www.bilibili.com/video/BV1wD4y1o7AS/?p=199&spm_id_from=333.880.my_history.page.click&vd_source=fd73aeb4b5207c8de46a320a1b47ec3f

**Comment by nICEnnnnnnnLee** [comment]
该链接本地复现没有问题。  

很难想象会出现这种情况，请确认一下：  
+ ***你是否使用的是本项目所对应的程序？*** 
请程序右上角`关于` -> `作品信息`，获取`版本信息`和`编译信息`，并回复。

在此基础上：
+ 输入该链接并确认后，在弹出的视频信息页面，分p数量是**100**个，还是**200**个？
+ 在批量下载后，到下载终止为止，下载面板的总任务有多少个？  
+ 下载面板的任务是否都是成功下载？

+ 关闭并重启程序，再次重试下载该链接，重新回复上述三个问题
+ 这次的结果有没有推进总下载进度，比如 `100/200` -> `200/200`？

另，如果可以的话，请附上log(可以不登录)

**Comment by chen12345chen** [comment]
在我更新了版本之后下载成功了。如果需要log日志请回复log日志存放路径。不需要的话我会明天关闭议题。
