### ISSUE TITLE
自定义文件名中参数listName返回为空

### ISSUE THREAD

**Issue by lsq** [nICEnnnnnnnLee/BilibiliDown#208]
**我已经确认**
- 使用的当前版本为最新版本
- 使用最新的CI版本仍然存在该问题[CI传送门](https://github.com/nICEnnnnnnnLee/BilibiliDown/actions/workflows/pre-release-artifacts.yml)
- issue区没有类似的情况（有的话请直接去该问题讨论）
- 我已经阅读过[帮助文档](https://nicennnnnnnlee.github.io/BilibiliDown/guide/quick-start/what-is-BilibiliDown)/[备用帮助文档](https://bili.nicelee.top/BilibiliDown/guide/quick-start/what-is-BilibiliDown)

**问题描述**
用最亲版本下载这个`https://www.bilibili.com/video/BV1EN411B7ZR`视频合集，配置
`(:listName 0_listName\)UpName\avTitle-(:favTime favTime-)pAv2-qn`
下载结果路径
`D:\Backup\Documents\bilibili\0xCC说逆向\逆向编程-汇编语言零基础入门教程-p01-80.mp4`
实际想要保存的路径是：
`D:\Backup\Documents\bilibili\逆向编程-汇编语言零基础入门教程\0xCC说逆向\逆向编程-汇编语言零基础入门教程-p01-80.mp4`

**相关信息**

+ 相关链接或者BV号
`https://www.bilibili.com/video/BV1EN411B7ZR`

**Comment by nICEnnnnnnnLee** [comment]
这种不是合集，是一个视频有多个分p。

合集视频之一应该类似于`https://www.bilibili.com/video/BV1Cv4y1g7dG/`.  
这个时候如果想要下载合集，需要点击获取链接
![2024730955382](https://github.com/user-attachments/assets/c28315e8-a502-4dbc-a83a-92b39608efd7)

`https://space.bilibili.com/593987248/channel/collectiondetail?sid=508765`
