### ISSUE TITLE
能否增加去水印功能

### ISSUE THREAD

**Issue by nannanness** [nICEnnnnnnnLee/BilibiliDown#209]
**我已经确认**
- 使用的当前版本为最新版本
- 使用最新的CI版本仍然存在该问题[CI传送门](https://github.com/nICEnnnnnnnLee/BilibiliDown/actions/workflows/pre-release-artifacts.yml)
- issue区没有类似的情况（有的话请直接去该问题讨论）
- 我已经阅读过[帮助文档](https://nicennnnnnnlee.github.io/BilibiliDown/guide/quick-start/what-is-BilibiliDown)/[备用帮助文档](https://bili.nicelee.top/BilibiliDown/guide/quick-start/what-is-BilibiliDown)

**问题描述**
请尽量详细地描述问题，以告诉如何复现，方便定位问题。

**相关信息**
+ 当前系统(windows/linux等)
+ java版本
+ 相关链接或者BV号
+ 账号是否登录
+ 在网页端观看是否存在问题
+ 是否存在自定义parsers
+ 相关log
  + 如何抓log请参考[Wiki-How to log](https://github.com/nICEnnnnnnnLee/BilibiliDown/wiki/How-to-log)

```
请在发表issue前进行预览，将影响排版的内容放到这里
```

**Comment by nICEnnnnnnnLee** [comment]
本程序对视频的处理仅限于音视频合并封装成mp4，进一步的处理不在考虑范围内。  

如果你有去水印的需求，可以百度`ffmpeg 去水印`。或者硬件条件好的可以尝试AI去水印工具，比如`propainter`等等。
