### ISSUE TITLE
配置无法保存，重启后还是原始配置

### ISSUE THREAD

**Issue by springculture** [nICEnnnnnnnLee/BilibiliDown#216]
路径在config文件里改了，想把声音关掉

版本信息: v6.34

**Comment by nICEnnnnnnnLee** [comment]
> 路径在config文件里改了

什么路径，哪个config文件？
如果你说的是`指定数据文件夹`，必须通过jvm参数指定，然后程序才能读取该文件夹下的配置文件。


> 想把声音关掉

修改`config/app.config`配置:
```
bilibili.download.playSound = false
```
或者直接通过配置面板修改保存

**Comment by springculture** [comment]
就是存储路径。
感谢已经能关掉声音了。

> 或者直接通过配置面板修改保存
在配置面板修改不生效。

**Comment by nICEnnnnnnnLee** [comment]
`v6.33`引入了一个bug，导致配置面板失效。可以参考下图，鼠标移动悬停在文字上获取`key`，然后手动修改`config/app.config`
![图片](https://github.com/user-attachments/assets/b0f0def4-2d1c-4453-8119-e85061745c0f)


或者下载CI版本<https://github.com/nICEnnnnnnnLee/BilibiliDown/actions/runs/10756766214>，解压缩后将`INeedBiliAV.jar`替换掉旧的即可。
