### ISSUE TITLE
请问如何在一键下载的时候不显示下载完成的对话框？

### ISSUE THREAD

**Issue by 4965898** [nICEnnnnnnnLee/BilibiliDown#217]
**问题描述**
一键下载时不停弹出对话框，需要点击后才会继续下载，如何使其不显示就能一直下载直至下载完成？
```

**Comment by nICEnnnnnnnLee** [comment]
```
[url:xxxxx]
...其它配置
stop.alert = false
```

另调查一下，你是如何知道怎么样一键下载的？

**Comment by 4965898** [comment]
> ```
> [url:xxxxx]
> ...其它配置
> stop.alert = false
> ```
> 
> 另调查一下，你是如何知道怎么样一键下载的？

不好意思，我以为这行代码只能用于收藏夹，单个视频不适用，文档写的是“# 表示在每下完一个收藏夹，就弹出一次提示
”
一键下载当然是看文档结合GPT自己写的代码
软件很棒，我经常用👍
