### ISSUE TITLE
rename.bat 这个找不到

### ISSUE THREAD

**Issue by sunfos** [nICEnnnnnnnLee/BilibiliDown#22]
不能重命名，文件找不到这个“rename.bat”

**Comment by nICEnnnnnnnLee** [comment]
+ 现在的默认配置是下载完毕后自动重命名，所以不会生成`rename.bat`
+ 请帮忙协助定位一下错误：  
     + 描述一下系统环境/Java环境
     + 提供一下`config/app.config`的具体信息
     + 下载是否已经成功？失败的话不重命名是正常的(下载界面成功的话是绿色)
     + 是否是所有下载的视频都不能重命名？如果是特例，请提供具体av号或链接
     +  运行`run-UI-debug.bat`，复现一下操作，将最后的部分log贴出
     + 将`config/app.config`的配置文件中重命名设置更改为false，然后贴出`rename.bat`的运行结果
    ```
     bilibili.name.doAfterComplete = false
    ```
