### ISSUE TITLE
右上角 优先清晰度 配置无效

### ISSUE THREAD

**Issue by freemedom** [nICEnnnnnnnLee/BilibiliDown#220]
**我已经确认**
- 使用的当前版本为最新版本
- 使用最新的CI版本仍然存在该问题[CI传送门](https://github.com/nICEnnnnnnnLee/BilibiliDown/actions/workflows/pre-release-artifacts.yml)
- issue区没有类似的情况（有的话请直接去该问题讨论）
- 我已经阅读过[帮助文档](https://nicennnnnnnlee.github.io/BilibiliDown/guide/quick-start/what-is-BilibiliDown)/[备用帮助文档](https://bili.nicelee.top/BilibiliDown/guide/quick-start/what-is-BilibiliDown)

**问题描述**
右上角 优先清晰度 配置无效

**相关信息**
+ 当前系统 windows
+ java版本
+ 相关链接或者BV号 https://space.bilibili.com/13127303/video?tid=0&special_type=&pn=1&keyword=&order=click
+ 账号是否登录 否

**Comment by freemedom** [comment]
我设置的是"弹幕"，但是实际下载下来的还是（1080p）的视频

**Comment by nICEnnnnnnnLee** [comment]
批量下载按钮旁边都标了优先清晰度是`1080p`，你点击的时候改一下。
![q1](https://github.com/user-attachments/assets/cf6eab68-3098-4b0d-b982-d57eb8e0155b)

右上角清晰度修改适用于右上角的`一键配置`和`批量下载Tab页`以及`按周期计划下载`
![图片](https://github.com/user-attachments/assets/c4b378de-fb7e-4c7c-a6ee-f3addf7de316)

**Comment by freemedom** [comment]
ok, 懂了。我以为右上角的配置会覆盖标签页里边的配置
