### ISSUE TITLE
希望下载的收藏夹里的合集的命名默认和网页上一致

### ISSUE THREAD

**Issue by wei8991526** [nICEnnnnnnnLee/BilibiliDown#222]
**我已经确认**
- 使用的当前版本为最新版本
- 使用最新的CI版本仍然存在该问题[CI传送门](https://github.com/nICEnnnnnnnLee/BilibiliDown/actions/workflows/pre-release-artifacts.yml)
- issue区没有类似的情况（有的话请直接去该问题讨论）
- 我已经阅读过[帮助文档](https://nicennnnnnnlee.github.io/BilibiliDown/guide/quick-start/what-is-BilibiliDown)/[备用帮助文档](https://bili.nicelee.top/BilibiliDown/guide/quick-start/what-is-BilibiliDown)

**问题描述**
请尽量详细地描述问题，以告诉如何复现，方便定位问题。

**相关信息**
+ 当前系统(windows/linux等)
+ java版本
+ 相关链接或者BV号
+ 账号是否登录
+ 在网页端观看是否存在问题
+ 是否存在自定义parsers
+ 相关log
  + 如何抓log请参考[Wiki-How to log](https://github.com/nICEnnnnnnnLee/BilibiliDown/wiki/How-to-log)

```
请在发表issue前进行预览，将影响排版的内容放到这里
```

**Comment by nICEnnnnnnnLee** [comment]
看issue跟做阅读理解一样，emotional damage。  

这边建议这样提issue：  
+ 使用链接 `https://space.bilibili.com/40545158/favlist?fid=1019804358&ftype=create`  
+ 第`1`页的第`2`个视频，BV号为`BV18i4y1377o`  
+ 实际标题为`【官人说电影】《黑夜传说5：血战》女主被裹成木乃伊死而复生 竟然有了瞬移技能 带领吸血鬼战胜狼人`  
+ 预期标题为 xxx


---

+ 我没见过收藏夹里还能嵌套有合集的。如果有，请参照上方提供链接及具体描述。  
+ 如果你说的合集指的是多p视频，请参考`自定义文件名`中的`clipTitle`。
你需要注意，这样很容易导致文件路径过长。
参考文档链接我就不放了。

**Comment by nICEnnnnnnnLee** [comment]
> @nICEnnnnnnnLee 你好，想请问下，文档是用什么生成的呀？挺好的

@heihei180 Vitepress
