### ISSUE TITLE
添加docker部署支持

### ISSUE THREAD

**Issue by xiezh123** [nICEnnnnnnnLee/BilibiliDown#224]
主要是docker方便部署

**Comment by nICEnnnnnnnLee** [comment]
我很难理解这种应用场景。  
如果你实在需要，可以：    
+ 拉一个支持`VNC + java`的镜像，或者拉一个支持`VNC`的镜像到本地，再在镜像里面安装java环境
+ 下载本项目release并解压(镜像内外均可，外部在运行的时候需要挂载)
+ 利用docker的Java环境运行本程序
