### ISSUE TITLE
合辑视频显示不出来，批量下载无效

### ISSUE THREAD

**Issue by lsq** [nICEnnnnnnnLee/BilibiliDown#225]
![image](https://github.com/user-attachments/assets/06458d37-3ecd-4e9b-a15d-c7b3f89cfda9)
在win10上用最新的6.35，会出现合辑视频加载不了，能加载的点击批量下载，下载列表没有出现任务；
采用的链接`https://space.bilibili.com/593987248/channel/collectiondetail?sid=508765`

**Comment by nICEnnnnnnnLee** [comment]
该问题在 <https://github.com/nICEnnnnnnnLee/BilibiliDown/actions/runs/11366563508> 中修复

**Comment by lsq** [comment]
测试可以下载了
