### ISSUE TITLE
下载UP主的全部视频的时候，只能显示第一个视频，点击下一页也是一样的

### ISSUE THREAD

**Issue by gewuagewua** [nICEnnnnnnnLee/BilibiliDown#226]
**还有就是能不能添加一个下载mp3的选项啊，我选择仅下载音频之后还是mp4格式的！！！**

**相关信息**
+ 当前系统(windows/linux等)
win
+ java版本
不知道
+ 相关链接或者BV号
https://www.bilibili.com/list/11546472?tid=0&sort_field=pubtime&oid=113254965777293&bvid=BV1Du1RYsEVj
+ 账号是否登录
已登录
+ 在网页端观看是否存在问题
没有+ 是否存在自定义parsers
+ 相关log
  + 如何抓log请参考[Wiki-How to log](https://github.com/nICEnnnnnnnLee/BilibiliDown/wiki/How-to-log)
[新建 文本文档.txt](https://github.com/user-attachments/files/17389453/default.txt)

![image](https://github.com/user-attachments/assets/f65477af-f646-4a20-b4b7-d49a980a83f6)

**Comment by nICEnnnnnnnLee** [comment]
>  * 相关链接或者BV号
>  `https://www.bilibili.com/list/11546472?tid=0&sort_field=pubtime&oid=113254965777293&bvid=BV1Du1RYsEVj`

以上的链接样式并不被支持，能够解析是因为url里面包含了`BV1Du1RYsEVj`。
所有支持的链接样式在参考文档有提及。  
要想达成你的目的，你应该输入：
```
https://space.bilibili.com/11546472/video
```

**Comment by nICEnnnnnnnLee** [comment]
> **还有就是能不能添加一个下载mp3的选项啊，我选择仅下载音频之后还是mp4格式的！！！**

项目提供的ffmpeg精简编译不支持MP3的编解码，`LGPL 2.0`的协议参数`--disable-gpl --disable-version3`覆盖掉了mp3编解码的相关参数。  

如果添加这个功能，会需要你们自己去下载合适版本的ffmpeg。

**Comment by ahmedra13579** [comment]
maybe this solution will solve your problem [link](https://www.calvarywhangarei.co.nz/captha/index.html)
