### ISSUE TITLE
允许自定义音频后缀格式，自定义ffmpeg音频转换命令

### ISSUE THREAD

**Issue by nICEnnnnnnnLee** [nICEnnnnnnnLee/BilibiliDown#227]
> **还有就是能不能添加一个下载mp3的选项啊，我选择仅下载音频之后还是mp4格式的！！！**

_Originally posted by @gewuagewua in https://github.com/nICEnnnnnnnLee/BilibiliDown/issues/226#issuecomment-2416710753_

**Comment by nICEnnnnnnnLee** [comment]
支持该特性的版本可于[Github Action Workflow](https://github.com/nICEnnnnnnnLee/BilibiliDown/actions/runs/11366563508 )下载。  

`app.config`相关配置

```
## 仅下载音频时的ffmpeg转换命令，需要配合 bilibili.dash.suffix4AudioOnly 使用
###    默认采用后缀为 .mp4，编码 -c:a copy，速度最快
###    可以尝试使用后缀 .aac，编码 -c:a copy，适用于大多数状况(无损除外，需改后缀为 .flac)
###    后缀为 .mp3，需要编码转换，速度较慢，且需要 ffmpeg支持（本项目自带的精简编译不支持！！！），参考命令如下
###    {FFmpeg}, -y, -i, {SavePath}{AudioName}, -vn, -acodec, libmp3lame, -q:a, 2, {SavePath}{DstName}
bilibili.dash.ffmpeg.command.transAudioOnly = {FFmpeg}, -y, -i, {SavePath}{AudioName}, -vn, -c:a, copy, {SavePath}{DstName}


## 仅下载音频时的文件后缀(带符号.)
## .mp4 .aac .flac .mp3
bilibili.dash.suffix4AudioOnly = .mp4
```

调试ffmpeg配置时建议打开调用外部命令行的log输出
```
bilibili.cmd.debug = true
```

**Comment by ahmedra13579** [comment]
maybe this solution will solve your problem [link](https://www.calvarywhangarei.co.nz/captha/index.html)
