### ISSUE TITLE
希望增加CLI 或者http api

### ISSUE THREAD

**Issue by ZanePoe** [nICEnnnnnnnLee/BilibiliDown#231]
我看到程序已经添加了一键配置和周期性一键批量下载等等功能，说明作者不简单只是把这个程序当做一般的下载器使用，而是希望有更多的玩法。
建议给程序暴露 http api接口，这样可玩性就更高了！

**Comment by nICEnnnnnnnLee** [comment]
程序的下载逻辑(特别是任务管理)和GUI高度耦合，增加http api也撇不开这部分。
如果想要`增加CLI 或者http api`，建议找找其它项目。
