### ISSUE TITLE
字幕文件无法下载

### ISSUE THREAD

**Issue by pawadali** [nICEnnnnnnnLee/BilibiliDown#232]
**我已经确认**
- 使用的当前版本为最新版本
- 使用最新的CI版本仍然存在该问题[CI传送门](https://github.com/nICEnnnnnnnLee/BilibiliDown/actions/workflows/pre-release-artifacts.yml)
- issue区没有类似的情况（有的话请直接去该问题讨论）
- 我已经阅读过[帮助文档](https://nicennnnnnnlee.github.io/BilibiliDown/guide/quick-start/what-is-BilibiliDown)/[备用帮助文档](https://bili.nicelee.top/BilibiliDown/guide/quick-start/what-is-BilibiliDown)

**问题描述**

【字幕文件突然无法下载了，今天从6.33版本下载失败，更新到最新6.36依然失败，视频文件可以正常下载，失败情况如下图所示，视频文件已经先下载过了一遍并生成对应的文件夹，之前下载字幕文件 也会在之后存入对应文件夹中】

![2024年11 01日-19时1分-48 ](https://github.com/user-attachments/assets/4c8082b6-72ab-4ce1-9eb0-98ef336476b4)

**Comment by nICEnnnnnnnLee** [comment]
问题在 <https://github.com/nICEnnnnnnnLee/BilibiliDown/actions/runs/11642537813> 中修复。  

现在字幕需要登录才能下载。
如果视频有多个字幕，请修改配置`bilibili.cc.lang`匹配你想要的。
AI字幕是`ai-en`、`ai-zh`之类，和普通的`zh-CN`这种有点区别

**Comment by pawadali** [comment]
谢谢大佬！那个包我替换后，字幕能下载了，但是这个是什么问题
![image](https://github.com/user-attachments/assets/a3c215dd-a6a9-492c-9884-38d7c71f44c4)

**Comment by pawadali** [comment]
> 谢谢大佬！那个包我替换后，字幕能下载了，但是这个是什么问题 ![image](https://private-user-images.githubusercontent.com/187018521/382489379-a3c215dd-a6a9-492c-9884-38d7c71f44c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NjczNzYsIm5iZiI6MTczMDU2NzA3NiwicGF0aCI6Ii8xODcwMTg1MjEvMzgyNDg5Mzc5LWEzYzIxNWRkLWE2YTktNDkyYy05ODg0LTM4ZDdjNzFmNDRjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQxNzA0MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zY2RjYTEwYWRjZjQ2MzRlYTA0OWQyZTlmYzI4ZWZjMGUxMjcwMTNhNGMyYTU1YWE0ZWYzNjI4NjU2NTA0ODhlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.48F4arK3SOrKXBLRdxjxhrBQKqnZTNb6JX0WS7rezH0)

这个下载字幕时会一直跳出来，下载视频不会

**Comment by pawadali** [comment]
![image](https://github.com/user-attachments/assets/bba271b1-707b-436e-9d8b-33814e7e30b5)
图在这

**Comment by nICEnnnnnnnLee** [comment]
视频没有字幕，但是你又发起了字幕下载请求，就报这个错误。

**Comment by pawadali** [comment]
哦哦原来如此，因为我都是手动批量完视频再备份字幕的，以前倒是不会出现这个
