### ISSUE TITLE
如何配置一键下载里的限制特定日期的命令

### ISSUE THREAD

**Issue by gstar12** [nICEnnnnnnnLee/BilibiliDown#235]
**我已经确认**
- 使用的当前版本为最新版本
- 使用最新的CI版本仍然存在该问题[CI传送门](https://github.com/nICEnnnnnnnLee/BilibiliDown/actions/workflows/pre-release-artifacts.yml)
- issue区没有类似的情况（有的话请直接去该问题讨论）
- 我已经阅读过[帮助文档](https://nicennnnnnnlee.github.io/BilibiliDown/guide/quick-start/what-is-BilibiliDown)/[备用帮助文档](https://bili.nicelee.top/BilibiliDown/guide/quick-start/what-is-BilibiliDown)

**问题描述**
比如我的一键下载配置文件里的内容是几百条这样的信息：

[url:https://space.bilibili.com/1243455344]
#start.page = 1
#stop.condition = _:downloaded
download.condition = _!downloaded
stop.condition =  cTime>2024-06-01
stop.alert = false

[url:https://space.bilibili.com/378726898]
start.page = 1
#stop.condition = _:downloaded
download.condition = _!downloaded
stop.alert = false
stop.condition = cTime>2024-06-01

例如以上这种格式几百条，我想让stop.condition = cTime>2024-06-01这个命令生效，就是下载 时间大于2024-06-01之前的这个UP主的视频，但是这条命令加上后它是从2024年1月1日以后开始下载的，我这命令是不是格式不对啊，我在帮助文档里实在没看明白怎么才是正确的格式，我试下stop.condition = _:cTime>2024-06-01或者stop.condition = :cTime>2024-06-01这种格式，作者给个指导吧，我是没登陆的，是不是和没登陆账号有关系，但你这软件不登陆也能下1080P

**相关信息**

+ 当前系统(windows/linux等)
WIN10

+ java版本最新，之前版本也一样

+ 账号是否登录
否

**Comment by nICEnnnnnnnLee** [comment]
程序会从`start.page`页开始查询，直到遇到`stop.condition`的视频停止查询。
这期间查询到的满足`download.condition`的视频，会加入到下载队列。

如果有多个条件，行与行之间是或的关系；一行里面`,`分割的条件之间是与的关系
```
stop.condition = {c1},{c2},{c3}
stop.condition = {c4},{c5}
stop.condition = {c6}
```
上述配置下，在(c1 && c2 && c3) || (c4 && c5) || c6为真的情况下停止查询

另外，关于时间大小的判断，越早越小，若A早于B，则A小于B。把时间看成距离`1970-01-01`过了多久的时间戳，应该很好理解吧。

----

> 这条命令加上后它是从2024年1月1日以后开始下载的

`UP主所有视频`默认都是发布时间倒序进行查询的，也就是最新的在最前面被查到，在配置`stop.condition = cTime>2024-06-01`时，你不可能下载得到`2024年1月1日`的视频，除非该up在`2024-06-01`后再也没有发布过视频。

> `stop.condition = _:cTime>2024-06-01`或者`stop.condition = :cTime>2024-06-01`

没有这种配置写法

> 就是下载 时间大于2024-06-01之前的这个UP主的视频

`大于`和`之前`矛盾。
`download.condition = cTime<2024-06-01` 表示发布的时间在`2024-06-01`之前才下载

**Comment by gstar12** [comment]
就是说我的stop.condition = cTime>2024-06-01这种配置是没问题的，刚才我试了下：
[url:https://space.bilibili.com/268552373]
#海阔试车
start.page = 1
download.condition = _!downloaded
stop.condition = cTime<2024-06-01
stop.alert = false
还是可以下到2024-06-01以前的，它不会停止，理论上小于这个2024-06-01日期的视频就应该不下，因为遇到了停止条件，但它还是会下的，如下图：
![image](https://github.com/user-attachments/assets/dad3cfd5-a3b0-4cdc-8a78-d873b4eb5454)

download.condition = cTime<2024-06-01这种写法我是没想到的，我只是想到了用stop的写法，我用download.condition = cTime>2024-10-01的方法试了下，还是不行，下面是我的命令，它一直会下到2023-12-31号的日期才会停止，不知道哪里出错：
[url:https://space.bilibili.com/471993422]
#6GHz
start.page = 1
download.condition = cTime>2024-10-01
#stop.condition = cTime<2024-06-01
stop.alert = false

下面是图片
![image](https://github.com/user-attachments/assets/088aeb1d-1e1c-42bd-a46d-cc8f315f0726)
![image](https://github.com/user-attachments/assets/6c3e5e8b-2cb1-4175-9712-078ee62cdde0)
![image](https://github.com/user-attachments/assets/5f8c39f8-8fe6-4cbb-8d67-03a05715f12e)
![image](https://github.com/user-attachments/assets/fc068a54-dcfc-417a-93c0-7ed6d443ac09)
如果我的命令写法有问题，麻烦您直接贴出正确的写法

**Comment by nICEnnnnnnnLee** [comment]
这是当前程序的bug，配置里的`2024-06-01`会被错误地转成时间戳`1703952000000`，相当于`2023-12-31 0:0:0`。

请使用下面这个版本：
<https://github.com/nICEnnnnnnnLee/BilibiliDown/actions/runs/11866683859>
一个参考配置：
```
[url:https://space.bilibili.com/268552373]
#海阔试车
start.page = 1
stop.condition = page:30
stop.condition = cTime<2024-06-01
download.condition = cTime>2024-06-01
stop.alert = false
```

**Comment by gstar12** [comment]
谢谢大佬，辛苦了
