### ISSUE TITLE
自定义文件名：如需要显示分p文件名clipTitle，当clipTitle和视频标题avTitle一致时，如何做到只保留其一？

### ISSUE THREAD

**Issue by sgromemi** [nICEnnnnnnnLee/BilibiliDown#237]
如题，目前我写
`(:listName 0_listName\)avTitle-pAv2-(:clipTitle clipTitle-)qn-(:favTime favTime)`
但如果clipTitle和avTitle一致，就会把冗长的视频标题重复两次。
似乎是因为视频如果不存在分p，则clipTitle默认与avTitle相等。

可以通过自定义文件名的条件语句做到当clipTitle和视频标题avTitle一致时只保留其一吗？

**Comment by nICEnnnnnnnLee** [comment]
没办法做到，只能人工修改

**Comment by sgromemi** [comment]
> 没办法做到，只能人工修改

感谢回复。
