### ISSUE TITLE
部分视频链接解析后没有可下载的视频选项

### ISSUE THREAD

**Issue by siegtoule** [nICEnnnnnnnLee/BilibiliDown#240]
**我已经确认**
- 使用的当前版本为最新版本
- 使用最新的CI版本仍然存在该问题[CI传送门](https://github.com/nICEnnnnnnnLee/BilibiliDown/actions/workflows/pre-release-artifacts.yml)
- issue区没有类似的情况（有的话请直接去该问题讨论）
- 我已经阅读过[帮助文档](https://nicennnnnnnlee.github.io/BilibiliDown/guide/quick-start/what-is-BilibiliDown)/[备用帮助文档](https://bili.nicelee.top/BilibiliDown/guide/quick-start/what-is-BilibiliDown)

**问题描述**
请尽量详细地描述问题，以告诉如何复现，方便定位问题。

**相关信息**
+ 当前系统(windows/linux等)
+ java版本
+ 相关链接或者BV号
+ 账号是否登录
+ 在网页端观看是否存在问题
+ 是否存在自定义parsers
+ 相关log
  + 如何抓log请参考[Wiki-How to log](https://github.com/nICEnnnnnnnLee/BilibiliDown/wiki/How-to-log)

```
请在发表issue前进行预览，将影响排版的内容放到这里
```
链接：https://www.bilibili.com/video/BV1fx411x7QS
解析时并未报错，但是在下载界面却没有显示任何可以使用的下载选项：
![image](https://github.com/user-attachments/assets/ebca3c3f-aad2-436d-a2a6-b05363e7c732)
此视频在b站有数个可选清晰度，并且并非大会员独享
![image](https://github.com/user-attachments/assets/e3eba64e-22ae-4933-896c-72fe5bc79d6c)
尝试过清除repo.config但是没有作用
关闭重启程序也并不管用
程序为最新版本
![image](https://github.com/user-attachments/assets/1041e9aa-b6d7-4b81-b27b-aa34e6f1770c)
系统为win10
账户已经登陆，并非大会员
最开始发现这个问题是在批量下载此视频所在合集时，虽然显示有下载选项，但无论批量下载还是单独下载都无法下载此视频，没有报错，只是单纯不下载，还有其他几个视频也有相同问题，但绝大部分其余视频都能正常下载

**Comment by nICEnnnnnnnLee** [comment]
程序查询可用清晰度时没有传cookie，而这个视频不登录又看不了，所以获取不到清晰度。
