### ISSUE TITLE
SIGBUS 错误，访问无效内存

### ISSUE THREAD

**Issue by xiao1870040934** [nICEnnnnnnnLee/BilibiliDown#242]
**我已经确认**
- 使用的当前版本为最新版本
- 使用最新的CI版本仍然存在该问题[CI传送门](https://github.com/nICEnnnnnnnLee/BilibiliDown/actions/workflows/pre-release-artifacts.yml)
- issue区没有类似的情况（有的话请直接去该问题讨论）
- 我已经阅读过[帮助文档](https://nicennnnnnnlee.github.io/BilibiliDown/guide/quick-start/what-is-BilibiliDown)/[备用帮助文档](https://bili.nicelee.top/BilibiliDown/guide/quick-start/what-is-BilibiliDown)

**问题描述**
请尽量详细地描述问题，以告诉如何复现，方便定位问题。
不管是切换java版本还是BilibiliDown版本 程序启动失败，通过错误日志中提到的 BUS_ADRALN 错误代码表明程序尝试访问未对齐的内存地址。错误发生在 ImageIO 框架中，特别是在 IIOReadPlugin::callInitialize 函数内。
**相关信息**
+ 当前系统(windows/linux等)
Macos15.1 M2pro
+ java版本
8和11
+ 相关链接或者BV号
无
+ 账号是否登录
无
+ 是否存在自定义parsers
无
+ 相关log
   [log](https://gitee.com/chenjinxiao520/images/blob/master/test/hs_err_pid8520.log)

**Comment by nICEnnnnnnnLee** [comment]
程序不包含`native libraries`，log的stacktrace也没看出来从哪部分Java code调用崩溃的。

思来想去，只能提供以下建议：
+ 尝试关闭`最小化到系统托盘`功能
    在`config/app.config`中修改配置`bilibili.sysTray.enable = false`

+ 尝试更换入口类，使用以下命令行
    `java -Dfile.encoding=utf-8 -Dbilibili.prop.mainClass=nicelee.ui.FrameMain_v3_4 -Dhttps.protocols=TLSv1.2 -jar launch.jar`

+ 尝试使用别的JDK版本
    log中JDK Azul Zulu 11.66 (11.0.20.1)在于August 2023发布 <https://docs.azul.com/core/release/august-2023-11.0.20.1-17.0.8.1/release-notes>
    请尝试使用更新的或者更古老的版本。

**Comment by xiao1870040934** [comment]
切换入口类可以了 感谢
