### ISSUE TITLE
可以加入“监视剪切板”吗

### ISSUE THREAD

**Issue by zywzyw1234567** [nICEnnnnnnnLee/BilibiliDown#25]
复制网址就能进入下载页面？

**Comment by nICEnnnnnnnLee** [comment]
+ 个人觉得“监视剪贴板”是一件很冒犯的事情，占用资源且侵犯隐私
+ 个人觉得这是一个很鸡肋的功能：  
   + 如果量少，选中搜索框再`Ctrl+V`相较而言并不会麻烦太多  
   + 如果量多，应该可以转变为`收藏夹/UP主频道/UP所有视频下载`的使用场景

**Comment by zywzyw1234567** [comment]
> * 个人觉得“监视剪贴板”是一件很冒犯的事情，占用资源且侵犯隐私
> * 个人觉得这是一个很鸡肋的功能：
>   
>   * 如果量少，选中搜索框再`Ctrl+V`相较而言并不会麻烦太多
>   * 如果量多，应该可以转变为`收藏夹/UP主频道/UP所有视频下载`的使用场景

今天似乎up所有视频下载似乎显示不出来了。。。

**Comment by zywzyw1234567** [comment]
> * 个人觉得“监视剪贴板”是一件很冒犯的事情，占用资源且侵犯隐私
> * 个人觉得这是一个很鸡肋的功能：
>   
>   * 如果量少，选中搜索框再`Ctrl+V`相较而言并不会麻烦太多
>   * 如果量多，应该可以转变为`收藏夹/UP主频道/UP所有视频下载`的使用场景

那可否加入“稍后再看”收藏夹的批量下载？因为我是同时关注10个up，每隔一段时间下载一波更新，所以如果可以右键，就非常方便，或者可以不点进去，直接点稍后看，若有加入“稍后再看”收藏夹的批量下载，会比较舒服
