### ISSUE TITLE
如何再次下载“已下载的视频”

### ISSUE THREAD

**Issue by zywzyw1234567** [nICEnnnnnnnLee/BilibiliDown#29]
如题，哪怕设置成“false”，也只是不会显示重复，照样无法重复下载

**Comment by nICEnnnnnnnLee** [comment]
+ 先找到`config`文件夹，
    + 在`app.config`文件里面设置`bilibili.repo = off`
    + 或者删掉`repo.config`文件里面的对应记录，再重启/重新加载
