### ISSUE TITLE
下载收藏夹只能下载前面5个

### ISSUE THREAD

**Issue by reov** [nICEnnnnnnnLee/BilibiliDown#3]
![image](https://user-images.githubusercontent.com/47272954/56089497-57bc3b00-5ec6-11e9-937c-561f8e00cdc3.png)

**Comment by nICEnnnnnnnLee** [comment]
这是分页查询的。
你在链接后面加上 p=2, 就是第6 到10 个了

**Comment by nICEnnnnnnnLee** [comment]
或者每次查多一点，可以修改```app.config```文件里面的配置
```bilibili.pageSize = 5```

**Comment by nICEnnnnnnnLee** [comment]
> 
> 
> 这是分页查询的。
> 你在链接后面加上 p=2, 就是第6 到10 个了

比如
```https://space.bilibili.com/8741628/favlist?fid=101422828&ftype=create p=2```
或者
```ml101422828 p=2```

**Comment by reov** [comment]
修改config似乎没有用，还是只出来5个，

**Comment by nICEnnnnnnnLee** [comment]
> 
> 
> 修改config似乎没有用，还是只出来5个，
:confused: 好奇怪，我这儿没啥问题
![downFavsByOneClick](https://user-images.githubusercontent.com/19970934/56104981-b76d2180-5f6c-11e9-8c6b-69fa2aed9ab8.gif)

**Comment by nICEnnnnnnnLee** [comment]
> 
> 
> 修改config似乎没有用，还是只出来5个，

+ 修改完以后，可以运行一下程序文件夹里面的`run-UI-debug.bat`看一下参数
![viewConfig](https://user-images.githubusercontent.com/19970934/56105309-25feaf00-5f6e-11e9-917e-4584b3b61bf5.png)
+ 最后可以检查一下是不是快捷方式指错地方了...

**Comment by reov** [comment]
重新修改好了没有问题了，但是这种方法只能最多20，手动p23456是不是太麻烦了，我看youtube-dl下载列表是怎么搞的

**Comment by nICEnnnnnnnLee** [comment]
现在的问题是：

1. ~~这种方法只能最多20~~
    + 通过一定的逻辑处理多次查询实现，封装后可以实现超过20的效果   _**考虑中**_


2. ~~手动p23456是不是太麻烦了~~
    + 个人觉得手动输入方式不算很麻烦。。。使用的频率也不会很高
    + 如果一定要的话，可以考虑增加一个按钮 `搜索下一页`  _**TODO**_

3. 有没有必要实现一次请求大数量的视频信息?
    + 只要临时文件存在，会在上次的基础上继续进行。
    + 任务完成后，可以保存记录，防止重复下载 _**TODO**_
    + 以上，目前没有，也不会有计划实现下载任务状态的保存(个人感觉挺鸡肋)
    + 以上，程序关闭后未开始的任务实际上是抛弃的。   过多的任务计划没有意义


4. 收藏夹结果的展示方式
    + Tab页打开过多时，其实显示效果不是很好，而且也是有最大数量限制
    + ==> _放到一页里面?_ _**考虑中**_

**Comment by nICEnnnnnnnLee** [comment]
[V3.1](https://github.com/nICEnnnnnnnLee/BilibiliDown/releases/tag/V3.1)对以上都做了实现
