### ISSUE TITLE
B站好像有些变动，最近总下载不到想要的视频尺寸

### ISSUE THREAD

**Issue by Cloudptj** [nICEnnnnnnnLee/BilibiliDown#31]
最近下载1080p，总下成360，480p的。
有些视频无论下几次都会出现异常。

**Comment by nICEnnnnnnnLee** [comment]
> 最近下载1080p，总下成360，480p的。

能否提供一下更详细的信息:  
+ 账号是否登录？  
+ 在网页端观看时，是否有1080p的清晰度？  
+ 是否所有视频的1080p都无法下载（若不是，请提供BV号或链接）？  
+ 1080p变成低画质是否是偶然情况（即同一视频有时候可以下载高画质，有时候不行）？
+ 下载的视频在程序的判断里是否是1080p(即文件名是否包含`-80`字段)？
+ 将config文件夹下的`cookies.config`删除，并重新登录后，问题是否仍然复现？ 
+ 最近短时间内是否下载了大量的视频？

<hr/>


> 有些视频无论下几次都会出现异常。
+ 能提供具体BV号/链接嘛

**Comment by Cloudptj** [comment]
抱歉，报告问题那天几乎什么视频都下载不到1080p，油猴插件、谷歌扩张也一样，下下来的都是360和480p的，但当天晚上又能下到了。
关于下载出错的问题，BV号是：BV1Ss411h7Ge
我测试了几次，发现如果我修改了app.config里的下载路径，变成：
bilibili.savePath =  F:\BiliBili\
（我试过改别的路径名也会出错，不知BiliBili这一个）
刚开始还能下载，之后就会大量报错下载异常。
改回默认地址，那么只有第七个视频会出错，程序会将p7的三个part都下载，但是合并时会出错，没有把三个part都合并，只把part1移动到最终的目录里。

**Comment by nICEnnnnnnnLee** [comment]
会出现这个现象，大概有三个地方出了问题： 
+ 文件路径尾部没有加上`\`或者`/`  
`bilibili.savePath = F:\BiliBili\`会好一点点，报错会往下移  
**影响绝大部分视频合并**
+ 写flv合并的ffmpeg调用命令时，相对路径可以通过，某些绝对路径不行
**影响更改路径后的flv视频的下载合并**
+ ffmpeg本身不支持处理某些flv视频
这个，我也不能武断地说视频源本身有问题，毕竟能够正常播放。。。但可以肯定的是，所有使用了ffmpeg的下载工具都会有这个情况。囧
**影响较小，目前bilibili不支持m4s只有flv资源的情况就很少了，flv里面还不支持的更加罕见**

**Comment by Cloudptj** [comment]
斜杠我是加过的，回帖复制时漏了，加了斜杠还是会有问题，有一部分视频会下载成功，一部分报错。
反斜杠的路径名我还没试过。

视频合并的问题，你说的是对的，我手动运行了一下ffmpeg，p7确实合并不正确，其他视频都可以。

**Comment by nICEnnnnnnnLee** [comment]
+ Windows环境下，只要文件末尾带上`/`，那么flv合并的ffmpeg调用就没有问题，除了p7这种情况基本上都能处理。以下路径测试可行：  
```
bilibili.savePath = download/
bilibili.savePath = D:\BiliBili/
# V5.2版本处理后，下面这些也是可以的
bilibili.savePath = D:\BiliBili\
bilibili.savePath = download\
bilibili.savePath = D:\BiliBili
bilibili.savePath = download
```  
+ 当然，新版本`V5.2`flv合并默认改成自己写的了，理论上适用于各种情况。
如果有需要，可以修改设置以重新回到ffmpeg合并flv
```
bilibili.flv.ffmpeg = true
```
