### ISSUE TITLE
字幕下载是不是不能批量下载？

### ISSUE THREAD

**Issue by Cloudptj** [nICEnnnnnnnLee/BilibiliDown#33]
以前没用过字幕下载的功能，今天用了下，发现只能下载第一个视频的字幕，似乎不能批量下载？
以下两个是下载视频的BV号
BV1bb411Y7HH
BV1De411s71p

**Comment by nICEnnnnnnnLee** [comment]
这确实是个问题

**Comment by nICEnnnnnnnLee** [comment]
+ 目前只能下载av的1p的字幕，多p不能下载，这是个bug
+ 关于批量下载，现在还在理顺思路，在想怎么实现改动最小😓
