### ISSUE TITLE
支持一下密码登录

### ISSUE THREAD

**Issue by PlexPt** [nICEnnnnnnnLee/BilibiliDown#34]
二维码有时候不方便

**Comment by nICEnnnnnnnLee** [comment]
+ 最近又调查估算了一下实现难度，发现使用app端的API接口能够获取token + cookies参数，所获取的cookies同样适用于WEB端的各种查询接口。里面的加盐加密算法移植到JVM环境不需要再额外采用比较重的依赖。  
+ 这个可以实现。但需要指出的是，当app端的参数与Web端不互通的时候，除非大改，否则将失效。

**Comment by kengwang** [comment]
![image](https://user-images.githubusercontent.com/30862240/83966027-68a9e600-a8ea-11ea-8ed3-4139c1188997.png)
某些时候密码登录存在问题,建议同时开启二维码登录入口

**Comment by nICEnnnnnnnLee** [comment]
这个对开启了设备验证没办法的
+ `bilibili.user.login = qr`二维码登录
+ `bilibili.user.login = pwd`密码登录
