### ISSUE TITLE
建议使用  Darcula 主题

### ISSUE THREAD

**Issue by PlexPt** [nICEnnnnnnnLee/BilibiliDown#35]
https://github.com/bulenkov/Darcula

**Comment by nICEnnnnnnnLee** [comment]
+ 先说点闲话。  
建这个项目的目的，一开始是学习爬虫，再就一个实践一下设计模式，当然最主要的是有阵子唧唧不能用(或者版本更新时失联)，再加上提的某些Feature那边一直咕咕咕，所以自己动手了咯。  
--
关于主题方面，其实只是一个很久以前的一个尝试，后续也没再继续整了。毕竟人机交互界面本就不是Java的强项，Swing更是比较老旧的技术了。我的宗旨是能用就行；有人提需求，如果工作量不大，我也看情况改改。  

+ 我尝试了一下这个主题，感觉很多地方不协调，需要适配，不会有计划使用这个

**Comment by nICEnnnnnnnLee** [comment]
[INeedBiliAV.DarculaLaf.jar.zip](https://github.com/nICEnnnnnnnLee/BilibiliDown/files/4734730/INeedBiliAV.DarculaLaf.jar.zip)

这个比较难看，本身背景图片以及颜色都是亮色的，与这种Dark色系不匹配，但我也不打算再改动了

**Comment by PlexPt** [comment]
![image](https://user-images.githubusercontent.com/15922823/83975357-1981a680-a926-11ea-8e21-57e00c8a852e.png)

**Comment by PlexPt** [comment]
https://github.com/CodeLunatic/bilibili_downloader
