### ISSUE TITLE
多线程下载支持

### ISSUE THREAD

**Issue by PlexPt** [nICEnnnnnnnLee/BilibiliDown#37]
https://segmentfault.com/a/1190000022883618

目前的下载方式太慢了。

**Comment by nICEnnnnnnnLee** [comment]
+ 你觉得所有资源都下得**太**慢，Web端H5播放源下载速度很慢吗？有必要开多线程吗？😕
+ 还是仅仅指老旧的FLV资源下得慢？

**Comment by PlexPt** [comment]
都慢， 10kb/s
看下你邮箱，方便交流

**Comment by PlexPt** [comment]
@nICEnnnnnnnLee

**Comment by nICEnnnnnnnLee** [comment]
+ 我不在QQ/微信上聊这个的
+ 音视频分离的源速度这么慢我无法理解，也不打算去深入探究；既然你提了多线程，那我就做一个简单的实现吧
