### ISSUE TITLE
收藏夹下载功能只能下载前五个视频

### ISSUE THREAD

**Issue by mawserver** [nICEnnnnnnnLee/BilibiliDown#39]

**Comment by nICEnnnnnnnLee** [comment]
+ 首页有个下一页按钮，或者在链接后面直接加上p=2之类的
+ 想一次打开多一点页面，在`config/app.config`中设置分页查询的大小
```
bilibili.pageSize = 5
```
+ 不建议设置得太大，因为会为每个av查询可用清晰度，一般来说这会产生(1~2)*pageSize 个网络请求

**Comment by mawserver** [comment]
> 
> 
>     * 首页有个下一页按钮，或者在链接后面直接加上p=2之类的
> 
>     * 想一次打开多一点页面，在`config/app.config`中设置分页查询的大小
> 
> 
> ```
> bilibili.pageSize = 5
> ```
> 
>     * 不建议设置得太大，因为会为每个av查询可用清晰度，一般来说这会产生(1~2)*pageSize 个网络请求

🆗
