### ISSUE TITLE
关于xxx只能下载前五个视频的问题

### ISSUE THREAD

**Issue by nICEnnnnnnnLee** [nICEnnnnnnnLee/BilibiliDown#40]
这个问题被问了很多遍，再次统一回复一下，请不要再问了。
+ [#3 下载收藏夹只能下载前面5个](https://github.com/nICEnnnnnnnLee/BilibiliDown/issues/3#issuecomment-482950065)
+ [#19 请问批量下载功能是否可以进一步完善](https://github.com/nICEnnnnnnnLee/BilibiliDown/issues/19#issuecomment-557359222)
+ [#30 将up主的个人空间链接打开后，只会记录前5个视频](https://github.com/nICEnnnnnnnLee/BilibiliDown/issues/30#issuecomment-617261026)
+ [#38 能不能一键解析一个UP的所有视频？](https://github.com/nICEnnnnnnnLee/BilibiliDown/issues/38#issue-665241970)
+ [#39 收藏夹下载功能只能下载前五个视频](https://github.com/nICEnnnnnnnLee/BilibiliDown/issues/39#issuecomment-663971221)

**Comment by nICEnnnnnnnLee** [comment]
+ 首页有个下一页按钮，或者在链接后面直接加上p=2之类的，就可以查剩下的。
+ 想一次打开多一点页面，在`config/app.config`文件中设置分页查询的大小
```
bilibili.pageSize = 5
```
+ 不建议设置得太大，因为会为每个av查询可用清晰度，一般来说这会产生(1~2)*pageSize 个网络请求

**Comment by Urliuo** [comment]
现有的分页机制确实容易让人一下子反应不过来。建议把”下一页“放在列表页面下方，这样用户就自然意识到还可以往下翻了。

**Comment by cnscorpions** [comment]
好的正好看下，不过Java写的GUI 😂
