### ISSUE TITLE
想问问相簿能不能批量下载原图

### ISSUE THREAD

**Issue by awei4287** [nICEnnnnnnnLee/BilibiliDown#43]
比如https://space.bilibili.com/321409837/album
我直接把链接粘进去，提示解析失败了
输一个相册的链接https://h.bilibili.com/90971175
开了一个新窗口一直加载，内容都是空白

**Comment by nICEnnnnnnnLee** [comment]
刚测试了一下，相册的链接是可以解析的。
![bilibili](https://user-images.githubusercontent.com/19970934/93337870-48c87d80-f85c-11ea-87ed-77bcb25557c8.png)

某个Up主的全部相册的解析没有写，只支持以下两种
* `https://space.bilibili.com/[0-9]+/favlist?fid=albumfav` 相簿收藏夹√
* [`https://h.bilibili.com/38894082`](https://h.bilibili.com/38894082)  单个相簿√

**Comment by awei4287** [comment]
额，好吧。。
（虽然单个相簿我好像还是一直显示正在加载）

**Comment by nICEnnnnnnnLee** [comment]
Windows的话，麻烦试一试运行`run-UI-debug.bat`，看看控制台有啥输出

**Comment by awei4287** [comment]
![QQ截图20200917090048](https://user-images.githubusercontent.com/23376999/93407671-4a7a5b80-f8c5-11ea-9177-e7b342df9cc1.png)

**Comment by awei4287** [comment]
![QQ截图20200917091048](https://user-images.githubusercontent.com/23376999/93407950-fcb22300-f8c5-11ea-945b-9e5fe9eb119a.png)
![QQ截图20200917091235](https://user-images.githubusercontent.com/23376999/93407960-03d93100-f8c6-11ea-88f3-1f1af6fe2307.png)
