### ISSUE TITLE
怎么自己生成文件夹

### ISSUE THREAD

**Issue by baoziL** [nICEnnnnnnnLee/BilibiliDown#44]
config找不到修改项

**Comment by nICEnnnnnnnLee** [comment]
https://github.com/nICEnnnnnnnLee/BilibiliDown/blob/8d87c9239589f817048be0e88cdf50011c9da1e9/release/config/app.config#L60-L62

https://github.com/nICEnnnnnnnLee/BilibiliDown/blob/8d87c9239589f817048be0e88cdf50011c9da1e9/release/config/app.config#L17
