### ISSUE TITLE
 现在下载不了高清的文件，之前还可以的

### ISSUE THREAD

**Issue by sky90038528** [nICEnnnnnnnLee/BilibiliDown#52]
现在下载的是低分辨率的，高清的下载不了

**Comment by nICEnnnnnnnLee** [comment]
刚刚测试了一下，似乎清晰度没有问题。请再确认：
+ 是否登录，或者cookie是否过期 
<hr/>

如果已经登录，请删除 `config/cookies.config` 后以扫码的方式登录后再尝试一次。
<hr/>

如果仍旧存在清晰度问题，请尽可能全的提供以下信息：
+ 相关链接或者BV号
+ 所在地域`国内/国外`
+ 是否存在自定义`parsers`
+ 相关log
  + windows下，运行`run-UI-debug.bat`，复现以后，复制一下控制台的输出
  + 其它平台，控制台cd到目录后`java -Dfile.encoding=utf-8 -jar INeedBiliAV.jar`，复现以后，复制一下控制台的输出
