### ISSUE TITLE
查找界面只出现了字幕弹幕按钮无法启动下载

### ISSUE THREAD

**Issue by Rebale** [nICEnnnnnnnLee/BilibiliDown#54]
输入地址点击查找后，界面只出现了字幕弹幕按钮，没有原本的清晰度选项，也无法启动下载

**Comment by nICEnnnnnnnLee** [comment]
请问你的账号在**网页端**是否**能够观看**该链接视频？

**Comment by Rebale** [comment]
> 请问你的账号在**网页端**是否**能够观看**该链接视频？

可以的。

**Comment by nICEnnnnnnnLee** [comment]
能发一下链接吗？

**Comment by Rebale** [comment]
> 能发一下链接吗？

我换了几个都如此，我不认为是链接的问题。
space.bilibili.com/2223018/video

**Comment by nICEnnnnnnnLee** [comment]
我这里复现不了，windows下麻烦运行run-UI-debug.bat，复现以后，复制一下控制台的输出
![save](https://user-images.githubusercontent.com/19970934/107644260-2c692980-6cb2-11eb-8f3f-54fd3f13816a.png)

**Comment by Rebale** [comment]
> 我这里复现不了，windows下麻烦运行run-UI-debug.bat，复现以后，复制一下控制台的输出
> ![save](https://user-images.githubusercontent.com/19970934/107644260-2c692980-6cb2-11eb-8f3f-54fd3f13816a.png)

直接运行bat吗，还是需要先打开软件抓取视频操作后再运行？

**Comment by Rebale** [comment]
我发现出现这种问题之后，把软件换个磁盘就好了，但问题是我已经把磁盘换一个遍，目前能用，再出问题就没有磁盘可换没办法了。

**Comment by Rebale** [comment]
现在是这种情况，连字幕按钮都没有了。
![捕获](https://user-images.githubusercontent.com/78908272/108166275-ec30fd80-712e-11eb-8646-9576e19705ab.PNG)

**Comment by nICEnnnnnnnLee** [comment]
> 
> 
> > 我这里复现不了，windows下麻烦运行run-UI-debug.bat，复现以后，复制一下控制台的输出
> 
> 直接运行bat吗，还是需要先打开软件抓取视频操作后再运行？

https://github.com/nICEnnnnnnnLee/BilibiliDown/wiki/How-to-log
