### ISSUE TITLE
bangumi类地址无法下载

### ISSUE THREAD

**Issue by zywzyw12345678** [nICEnnnnnnnLee/BilibiliDown#56]
https://www.bilibili.com/bangumi/play/ep307772?from=search&seid=3052299516190531859

这个地址无法下载，昨天还可以下载，今天就不行了

**Comment by nICEnnnnnnnLee** [comment]
自`v5.9`版本起不再支持这种链接类型的下载。
你可以使用`自定义各种链接解析`功能，或者回退到低版本

**Comment by zywzyw12345678** [comment]
什么是自定义各种链接解析？

二土 <notifications@github.com> 于 2021年3月9日周二 20:25写道：

**Comment by nICEnnnnnnnLee** [comment]
+ 这是我写的[解析](https://github.com/nICEnnnnnnnLee/BilibiliDown/tree/master/src/nicelee/bilibili/parsers/impl)  
+ 你可以参考，将自己的实现新建一个`parsers`文件夹放在里面。
以下是一个结构目录参考。
```
- ffmpeg.exe
- INeedBiliAV.jar
- run-UI-debug.bat
- run-UI.bat
- uninstall.bat
- update.bat
- config
    - app.config
    - cookies.config
    - repo.config
    - background.png
- parsers
    - parsers.ini
    - EPParser.java  // 你自己的实现
    - MdParser.java  // 你自己的实现
    - SSParser.java  // 你自己的实现
```
