### ISSUE TITLE
寻求以搜索结果批量下载的建议？

### ISSUE THREAD

**Issue by Jezzffihuter** [nICEnnnnnnnLee/BilibiliDown#57]
**我已经确认**
+ 使用的当前版本为最新版本
+ issue区没有类似的情况（有的话请直接去该问题讨论）

**问题描述**
首先很感谢程序的编写者~
本程序的使用体验很友好，而且大大节省了下载时间。
不过我在使用时，考虑到有两个功能，目前似乎还没有完满实现。如果能够增加上，或许会使程序更完满。
1. 在使用批量下载UP视频功能时，似乎网页的排序只能是“最新发布”，譬如针对https://space.bilibili.com/1276787/video ，即使选了“最多播放”，所下载的视频仍然按照“最新发布”排序。我理解这个问题可能不好解决，只是确认一下，是否按照“最多播放”依次批量下载的功能确实还没有实现？而未来是否有可能实现呢？
2. 据我尝试，目前似乎还不能实现按照特定分区（如https://www.bilibili.com/v/information ）或按照搜索关键词（https://search.bilibili.com/all?keyword=%E7%BE%8E%E5%9B%BD&from_source=nav_suggest_new ）批量下载视频。我也希望确认下，未来有无可能实现此类功能。
感谢大佬百忙之中抽空解答~

**相关信息**
+ 当前系统Windows 10家庭版
+ Java版本1.8.0_281-b09
+ 账号已经登录
+ 在网页端观看不存在问题
+ 不存在自定义parsers

**Comment by Jezzffihuter** [comment]
大佬好~能否有空时考虑下加入我所提的功能，可以有偿，详情可以加微信WCY18217712639交流，感谢

**Comment by nICEnnnnnnnLee** [comment]
+ 我不会在微信或QQ上讨论这些事情。
+ 这些需求从实现难度上都差不多，但我不会全部实现。
    
    >    在使用批量下载UP视频功能时，似乎网页的排序只能是“最新发布”...
    1. 这个可以有

    >    据我尝试，目前似乎还不能实现按照特定分区...
    2. 我的初衷是创造一个使用顺手的、面向唧唧er的应用，理念是`not offensive`。  
    ~~虽然经历一次重构和N次拓展，代码越来越臃肿，不合理的地方也越来越多，但预期在很长的时间内还在接受范围内~~  
   在我的理解里，
        + 我会因为某个视频喜欢上某个UP主爱屋及乌想下ta的全部视频
        + 我会想下载个人认为有用的全套课程或是喜欢的某个系列视频
        + 我会刷了一些视频，觉得有意思，就把它放到收藏夹或者稍后再看等待下载
        ... 
        + 但是，`按照特定分区(人气排行或最新投稿)`、`全局搜索关键词`这种，对将要下载的视频的了解想必不是很多。  
        我个人对这种毫无节制的松鼠收集癖好表示中立，即 不会实现它，也不排斥PR。

**Comment by nICEnnnnnnnLee** [comment]
+ 注意，以下仅针对`V6.0`版本，并不一定与以后的版本兼容。  
  当然，该功能应该会整合到后续版本当中。
+ 将下面的文件下载后，去掉txt后缀，新建一个`parsers`文件夹把它放进去即可实现下载UP视频功能时的顺序等功能
[URL4UPAllParser2.java.txt](https://github.com/nICEnnnnnnnLee/BilibiliDown/files/6120297/URL4UPAllParser2.java.txt)
```
- ffmpeg.exe
- INeedBiliAV.jar
- run-UI-debug.bat
- run-UI.bat
- uninstall.bat
- update.bat
- config
    - app.config
    - cookies.config
    - repo.config
    - background.png
- parsers
    - URL4UPAllParser2.java
 ```

+ 使用方法
行为与浏览器的链接一致。  
当然，B站只有在你点切换分区的时候浏览器的url才会改变，所以你可能需要自己动动手
```
https://space.bilibili.com/1276787/video?tid=0&keyword=&order=pubdate

以下这些参数可以是与浏览器里面的地址一致的，当然你也可以根据需要自己填写
- tid: 分区
  - 全部 0
  - 游戏 4
  - 知识 36
  - 生活 160
  ...

- keyword: 关键词

- order: 顺序
  - 最新发布 pubdate 
  - 最多点击 click 
  - 最多收藏 stow
```

**Comment by Jezzffihuter** [comment]
您好：
感谢回复。我已经将附件下载、去掉后缀（本身并未改动）并放入parsers文件夹。
![image](https://user-images.githubusercontent.com/65488456/112112415-77028d80-8bf0-11eb-9860-c4883fdbb950.png)

我现在可以实现用https://space.bilibili.com/1276787/video?tid=36下载up主的知识区投稿视频，可以实现用https://space.bilibili.com/1276787/video?keyword=dlc下载up主（视频题目）包含878的视频，非常感谢。
然而，我还有几个问题希望请教：
1. 浏览器中可以使用https://space.bilibili.com/1276787/video?tid=4&keyword=奥斯曼，但是在下载器中却无法识别中文字符（“奥斯曼”），直接输入也不行。
2. 在下载器中同时使用https://space.bilibili.com/1276787/video?tid=160&keyword=2，只能tid符合条件（“生活区”）的视频，而不能选出keyword符合条件（“2”）的视频，即似乎仅第一个参数有效。
3. 在下载器中使用https://space.bilibili.com/1276787/video?tid=0&keyword=&order=click，并不能按照“最多点击”降序排列。

抱歉花费您时间，非常感谢您百忙之中的回复！

**Comment by nICEnnnnnnnLee** [comment]
>     1. 浏览器中可以使用[https://space.bilibili.com/1276787/video?tid=4&keyword=奥斯曼](https://space.bilibili.com/1276787/video?tid=4&keyword=%E5%A5%A5%E6%96%AF%E6%9B%BC) ，但是在下载器中却无法识别中文字符（“奥斯曼”），直接输入也不行。
`https://space.bilibili.com/1276787/video?tid=4&keyword=奥斯曼`
![tid=4 keyword=奥斯曼](https://user-images.githubusercontent.com/19970934/112141942-f3a56400-8c10-11eb-9d13-2a6dd029b833.png)

`https://space.bilibili.com/1276787/video?tid=4&keyword=%E5%A5%A5%E6%96%AF%E6%9B%BC`
![tid=4 keyword=%E5%A5%A5%E6%96%AF%E6%9B%BC](https://user-images.githubusercontent.com/19970934/112141982-00c25300-8c11-11eb-8d15-738794466ba3.png)


>     2. 在下载器中同时使用https://space.bilibili.com/1276787/video?tid=160&keyword=2 ，只能tid符合条件（“生活区”）的视频，而不能选出keyword符合条件（“2”）的视频，即似乎仅第一个参数有效。

`https://space.bilibili.com/1276787/video?tid=160&keyword=2`
![tid=160 keyword=2](https://user-images.githubusercontent.com/19970934/112142023-0c157e80-8c11-11eb-9ddc-4a1fc0d89bf1.png)


>     3. 在下载器中使用https://space.bilibili.com/1276787/video?tid=0&keyword=&order=click ，并不能按照“最多点击”降序排列。

`https://space.bilibili.com/1276787/video?tid=0&keyword=&order=click`
![tid=0 keyword= order=click](https://user-images.githubusercontent.com/19970934/112142082-1c2d5e00-8c11-11eb-96f7-ef56c092a80d.png)

**Comment by nICEnnnnnnnLee** [comment]
请把结果图发出来，并附上log
[如何抓log？点这里](https://github.com/nICEnnnnnnnLee/BilibiliDown/wiki/How-to-log)

**Comment by nICEnnnnnnnLee** [comment]
如果你的情况是打开标签页发现**没有**有效内容，而不是内容不对，那么应该是返回的内容概率**乱码**引起的。

**Comment by Jezzffihuter** [comment]
> > ```
> > 1. 浏览器中可以使用[https://space.bilibili.com/1276787/video?tid=4&keyword=奥斯曼](https://space.bilibili.com/1276787/video?tid=4&keyword=%E5%A5%A5%E6%96%AF%E6%9B%BC) ，但是在下载器中却无法识别中文字符（“奥斯曼”），直接输入也不行。
> > ```
> 
> `https://space.bilibili.com/1276787/video?tid=4&keyword=奥斯曼`
> ![tid=4 keyword=奥斯曼](https://user-images.githubusercontent.com/19970934/112141942-f3a56400-8c10-11eb-9d13-2a6dd029b833.png)
> 
> `https://space.bilibili.com/1276787/video?tid=4&keyword=%E5%A5%A5%E6%96%AF%E6%9B%BC`
> ![tid=4 keyword=%E5%A5%A5%E6%96%AF%E6%9B%BC](https://user-images.githubusercontent.com/19970934/112141982-00c25300-8c11-11eb-8d15-738794466ba3.png)
> 
> > ```
> > 2. 在下载器中同时使用https://space.bilibili.com/1276787/video?tid=160&keyword=2 ，只能tid符合条件（“生活区”）的视频，而不能选出keyword符合条件（“2”）的视频，即似乎仅第一个参数有效。
> > ```
> 
> `https://space.bilibili.com/1276787/video?tid=160&keyword=2`
> ![tid=160 keyword=2](https://user-images.githubusercontent.com/19970934/112142023-0c157e80-8c11-11eb-9ddc-4a1fc0d89bf1.png)
> 
> > ```
> > 3. 在下载器中使用https://space.bilibili.com/1276787/video?tid=0&keyword=&order=click ，并不能按照“最多点击”降序排列。
> > ```
> 
> `https://space.bilibili.com/1276787/video?tid=0&keyword=&order=click`
> ![tid=0 keyword= order=click](https://user-images.githubusercontent.com/19970934/112142082-1c2d5e00-8c11-11eb-96f7-ef56c092a80d.png)

所提问题已经解决，非常感谢~

**Comment by Jezzffihuter** [comment]
你好，感谢此前帮助！

目前我发现搜索**https://space.bilibili.com/10330740/video?&keyword=特朗普** 
![image](https://user-images.githubusercontent.com/65488456/151706371-b390e096-f948-4129-8672-8de68a3ac80e.png)
会显示解析失败

而**https://space.bilibili.com/10330740/video?tid=0&keyword=特朗普** 会一直显示“正在加载中”
![image](https://user-images.githubusercontent.com/65488456/151706350-b68552cb-e7f4-4d09-bb1e-df05778162b6.png)

请问是否因为这个的结果过多（共有2250个视频）？
![image](https://user-images.githubusercontent.com/65488456/151706418-bcd1a669-ce1a-4ecc-8182-29f14d1794e3.png)

如何解决这个问题呢？
感谢，顺祝春节快乐！

**Comment by Jezzffihuter** [comment]
你好！我想下载B站上“”观察者网”UP发布的所有含“特朗普”关键词的720P视频（https://space.bilibili.com/10330740/video?tid=0&keyword=%E7%89%B9%E6%9C%97%E6%99%AE ，共2251个视频）。
![image](https://user-images.githubusercontent.com/65488456/153981563-41009fb1-f347-4063-9d89-caa8f3c7b2ca.png)

我可以加载出视频，但是下载时有大量错误（大约只能下到300-400个视频）。多次尝试“全部暂停”后“全部继续”也无效。
目前我设置的软件参数是：分页查询时，每页av个数=50，下载任务线程池大小=5，单个下载任务开启线程数=5。
电脑配置如下：
![image](https://user-images.githubusercontent.com/65488456/153982246-88a816b7-f5c9-42b7-b26c-b98b395471e5.png)

请问如何能够顺利下到全部视频呢？比如软件参数推荐如何调整，下载时有什么要注意的呢？
感谢解答！
