### ISSUE TITLE
如果你近期遇到了问题，请先看这个

### ISSUE THREAD

**Issue by nICEnnnnnnnLee** [nICEnnnnnnnLee/BilibiliDown#58]
+ 发现B站的API有一定概率会返回乱码，具体表现为：
    + cookie未失效的情况下，打开页面弹出登录窗口(扫码/密码)
    + 登录失败或没有反应
    + 登录成功后首页右上角没有显示头像等等
    + 输入内容后，新的标签页没有内容
    + 添加下载任务失败
    + 下载失败
    。。。
    总之就是突然不好用了

+ 怎样判断是由**乱码**引起的呢？
    + 通过`run-UI-debug.bat`打开本程序，照常操作  
    (如果没有发现问题那真是极好的，该干嘛干嘛)
    + 出现问题的时候观察一下命令窗口，如果你在里面发现了乱码，请来个+1 reaction
       因为我不确定是不是偶然的个别现象

+ 怎样处理这个问题呢？
    + 这个问题暂时没法解决
    + 请耐心等一段时间，不要有任何操作，然后再等一会可能就好了。。。

**Comment by nICEnnnnnnnLee** [comment]
目前发现2例：
1例应该算是确认：
https://github.com/nICEnnnnnnnLee/BilibiliLiveRecorder/issues/60#issuecomment-804863669_
1例有可能：
https://github.com/nICEnnnnnnnLee/BilibiliDown/issues/57#issuecomment-804887383_

**Comment by nICEnnnnnnnLee** [comment]
+ 该问题已在`V6.1`版本解决
+ 问题成因：
    + 在网络请求时，客户端一味的去模拟浏览器行为，声称了自己无法支持的解压方式。
    + 可能最近服务器端或者CDN升级什么的，有概率会以`br`方式压缩数据内容，导致客户端无法解码

**Comment by an-Underpriviliged-ZJUer** [comment]
刚用这个软件不久，请问能否批量下载视频封面呢？

**Comment by nICEnnnnnnnLee** [comment]
> 
> 
> 刚用这个软件不久，请问能否批量下载视频封面呢？

不能
