### ISSUE TITLE
如何才能不弹已下载

### ISSUE THREAD

**Issue by reov** [nICEnnnnnnnLee/BilibiliDown#6]
重复下载弹框多了关不过来

**Comment by nICEnnnnnnnLee** [comment]
+ 没有设计这个开关:joy:
+ 一个解决方案是：按住`Enter`键不放
+ 这个放到***TODO***里面，下个版本带进去好了

**Comment by nICEnnnnnnnLee** [comment]
增加了[V3.3](https://github.com/nICEnnnnnnnLee/BilibiliDown/releases/tag/V3.3)
*  增加弹出框提示开关，在配置文件里面设置后，可以不再提示
`bilibili.alert.isAlertIfDownloded = true/false`
*  弹出框增加关闭所有提示框按钮，点击可以关闭所有提示
![截图](https://user-images.githubusercontent.com/19970934/56848897-0d07dd80-6920-11e9-9786-6d0724ce34fc.png)

*  增加最大弹出框数量限制，超出后不再弹出提示（默认为5，可以自行更改）
`bilibili.alert.maxAlertPrompt = 5`

**Comment by reov** [comment]
当我下载一个999的收藏夹时，出现了一些状况，并不是所有的视频被重命名，而且有几个视频无法下载，无法合并

**Comment by reov** [comment]
而且下载时发现只要下载了，删了视频就不能重新下载

**Comment by nICEnnnnnnnLee** [comment]
> 
> 
> 当我下载一个999的收藏夹时，

+ 老铁，一次新建这么多任务不科学噢。。。量大的话，频繁的网络请求容易出现异常。

> 
> 
> 出现了一些状况，并不是所有的视频被重命名

+ 能不能提供一下，**收藏夹名称** + **未被重命名的avId** + `bilibili.name.format`，我看能不能复现
         -- 怀疑是长度过长或者 包含非法字符
+ 如果量很大的话，建议设置成`bilibili.name.doAfterComplete = false`，然后下载完成后人工运行`rename.bat`，这样重命名失败至少名称会有保存

**Comment by nICEnnnnnnnLee** [comment]
> 
> 
> 有几个视频无法下载，无法合并

+ 无法下载的原因可能有： 
    + 视频被和谐或已删除
![lost](https://user-images.githubusercontent.com/19970934/56850204-daff7700-6931-11e9-8ac1-34da0cf5f88e.png)
    + 没有权限下载(比如有的新番要大会员才能看）
    + 网络问题,过段时间再试(比如过于频繁的请求服务器，或者未知原因の抽风)
    + bug，请提供av号
+ 无法合并
    + 一般是视频没有下载完，单独重新再下载再试试(临时文件未删除的话，下载进度不会变)
    + 还不行，请提供av号和优先视频格式

**Comment by nICEnnnnnnnLee** [comment]
> 
> 
> 而且下载时发现只要下载了，删了视频就不能重新下载

+ ~~只要下载了，删了视频就不能重新下载~~             ×
       只要下载**完成**了，删了视频就不能重新下载    √
+ 这个功能是为了防止重复下载，不是很理解为什么要下两次:confused:
+ 如何关掉这个功能，[Wiki](https://github.com/nICEnnnnnnnLee/BilibiliDown/wiki)里面有
<details>
<summary>想下视频，但是提示我已经下载了？ ver>=3.1</summary>


* 请确认你真的没有下载？？
* 请确认是否下过该视频的另一种清晰度的版本？
    * 是 => `bilibili.definitionStrictMode = on`
    * 否，请继续
* 找到`config/repo.config`里的记录，把它删除 或者
* 关闭仓库模式 => `bilibili.repo = off`
</details>

**Comment by reov** [comment]
那这样的话能不能将下载失败的单独列出来，夹杂在列表很难找

**Comment by nICEnnnnnnnLee** [comment]
下载任务面板有个`删除已完成`的按钮，点这个就行了。（  除了临时文件，程序不会删除已经完成的视频

**Comment by nICEnnnnnnnLee** [comment]
我的意思是，删除掉已完成的，剩下的都是正在下的或者下载失败的

**Comment by nICEnnnnnnnLee** [comment]
如果想找已完成的列表话，可以按照上面所说改下配置，打开rename.bat查看

**Comment by nICEnnnnnnnLee** [comment]
> 
> 
> 那这样的话能不能将下载失败的单独列出来，夹杂在列表很难找

 @reov 现在[V3.4](https://github.com/nICEnnnnnnnLee/BilibiliDown/releases/tag/V3.4)下载失败颜色会变红色，比较容易区分

**Comment by nICEnnnnnnnLee** [comment]
+ 视频实际已经下下来了，但重命名失败，该问题可能会导致：
    + 用户可能无法较容易地识别出`已下载完成的文件av-qn-p.(flv|mp4)`，误以为下载失败；
    + `已下载完成的文件`的命名中视频清晰度标识有问题；
    + 想要的文件命名丢失；
    + 部分临时文件没有删除
    + 想要重新下载的时候提示已经下载(因为实际上视频文件已经完整下下来了)

**Comment by nICEnnnnnnnLee** [comment]
这个问题在[V3.5](https://github.com/nICEnnnnnnnLee/BilibiliDown/releases/tag/V3.5)已经解决
