### ISSUE TITLE
快速确认一下版本有无发错

### ISSUE THREAD

**Issue by Jezzffihuter** [nICEnnnnnnnLee/BilibiliDown#60]
**我已经确认**
+ 使用的当前版本为最新版本
+ issue区没有类似的情况（有的话请直接去该问题讨论）

**问题描述**
你好，感谢更新v6.1版。我从这里下载了v6.1软件https://github.com/nICEnnnnnnnLee/BilibiliDown/releases.
不过，我打开新更新的软件时，显示的是v4.5；甚至单个up主的视频都无法加载。
![image](https://user-images.githubusercontent.com/65488456/112301216-a8ed2000-8cd4-11eb-973e-eb6e1c4c0775.png)
例如搜索https://space.bilibili.com/1276787/video，显示加载错误。
![image](https://user-images.githubusercontent.com/65488456/112301391-d9cd5500-8cd4-11eb-9ea2-03964b7289ba.png)
因此我冒昧确认一下，v6.1版的软件有无发错成v4.5。
如果是我的疏忽，非常抱歉。

**Comment by nICEnnnnnnnLee** [comment]
+ 版本是由机器人根据代码自动生成的，`v6.1`版本里面的附件变成`v4.5`不大可能。  
  人工下载了附件看了下也没有问题。
+ 经本地检测，通过`v6.0`的版本检测升级`v6.1`也是可以的。

**Comment by Jezzffihuter** [comment]
你好，问题已经解决，非常感谢~
