### ISSUE TITLE
四个小问题（字幕下载，弹幕下载，封IP，视频基本信息）

### ISSUE THREAD

**Issue by Jezzffihuter** [nICEnnnnnnnLee/BilibiliDown#61]
**我已经确认**
+ 使用的当前版本为最新版本
+ issue区没有类似的情况（有的话请直接去该问题讨论）

**问题描述**
你好：
我有三个问题：
1. 我以https://space.bilibili.com/10330740/video?tid=0&page=1&keyword=%E7%BE%8E%E5%9B%BD%20%E7%96%AB%E6%83%85&order=pubdate 搜索，下载过1080p的第一页视频，但是后面删除了。我希望以相同链接下载720p的第一页视频，但是显示“已经下载过视频”，并未重新开始下载，而且重启程序也无效。
![image](https://user-images.githubusercontent.com/65488456/112708890-eaa5e280-8eef-11eb-8a1b-10f37ba609a7.png)
2. 我以https://space.bilibili.com/1276787/video?tid=4&keyword=2&order=pubdate 试验，不能进行批量字幕下载（点击无反应），并且似乎只能单独下载弹幕（而不能批量下载弹幕）。
![image](https://user-images.githubusercontent.com/65488456/112711880-bd186380-8f06-11eb-96e0-99dc4ba9e366.png)
3. 我下载某up的视频到第10页时https://space.bilibili.com/10330740/video?tid=0&page=22&keyword=%E7%BE%8E%E5%9B%BD%20%E7%96%AB%E6%83%85&order=pubdate p=10，无法显示下载界面，是否可能是连续下载封了IP？请问有无办法解决？
![image](https://user-images.githubusercontent.com/65488456/112712629-c657ff00-8f0b-11eb-931f-05208d1c11b7.png)
4. 请问一下文件命名规则问题。比如这个文件名《频遭白宫抹黑 福奇忍不住了：扯皮没意义，赶紧抗疫吧-pn295-p1-福奇修改-64》，原链接https://www.bilibili.com/video/BV1YD4y1S7pk 。64是指帧率、pn295是对应视频在搜索结果中的序号吧，不过“福奇修改”是什么意思呢？请问有没有办法看出视频的上传时间和播放数、最好能在文件名中输出呢？如此将有利于管理这些视频。
![image](https://user-images.githubusercontent.com/65488456/112719600-9cff9900-8f34-11eb-933b-9c149e593cbd.png)
![image](https://user-images.githubusercontent.com/65488456/112719732-53fc1480-8f35-11eb-9a0e-f787cb0a39ea.png)

非常感谢你在忙碌中的解答。

**相关信息**
+ 当前系统Win 10
+ 账号已经登录
+ 在网页端观看无问题

**Comment by nICEnnnnnnnLee** [comment]
+ 大部分问题的答案可以在[wiki](https://github.com/nICEnnnnnnnLee/BilibiliDown/wiki)中找到。
+ 请养成提问时附带log的好习惯。[How-to-log](https://github.com/nICEnnnnnnnLee/BilibiliDown/wiki/How-to-log)
<hr />
1.  

> 下载过1080p的第一页视频，但是后面删除了。我希望以相同链接下载720p的第一页视频，但是显示“已经下载过视频”

https://github.com/nICEnnnnnnnLee/BilibiliDown/blob/c4eaf9fb795f03a41ff7cba1ad28bd2644cfb367/release/config/app.config#L103-L115

2.

   > `https://space.bilibili.com/1276787/video?tid=4&keyword=2&order=pubdate` 不能进行批量字幕下载（点击无反应）

这里面的视频没有CC字幕
   > 并且似乎只能单独下载弹幕（而不能批量下载弹幕）

是的，弹幕只能单独下载，这只是一个测试功能

3. 

> 无法显示下载界面，是否可能是连续下载封了IP？请问有无办法解决？

+ 我自己也使用这个下视频的，我没有遇到过这种情况
+ 封ip的情况下，网页端观看会无法播放，出现`肥肠抱歉...`，这与描述不符
+ 预期log里面会出现 HTTP 请求返回 412 ，但信息不足，无法判断
+ 你可以将`app.config`里面的`默认最大同时下载数由为3改为1`，  
   同时不要短时间内新建大量标签页(也就是狂点下一页)

4.

> 不过“福奇修改”是什么意思呢？

你可以自定义文件名称
https://github.com/nICEnnnnnnnLee/BilibiliDown/blob/c4eaf9fb795f03a41ff7cba1ad28bd2644cfb367/release/config/app.config#L1-L18

> 请问有没有办法看出视频的上传时间和播放数、最好能在文件名中输出呢

没有，从设计的时候就没有考虑过要获取这些信息

**Comment by Jezzffihuter** [comment]
你好：

感谢回复，问题都已经解决。
追加一个小问题：
我想一目了然地判断所下载的稿件发布于2020年3月23日之前还是之后，但是又没有时间去查大量原始信息。
我看到https://www.bilibili.com/read/cv5167957/ ，2020年3月23日起，AV号升级为BV号。
因此我推断，3月23日之前的视频只有AV号，而3月23日之后的视频只有BV号。我想通过文件命名看出来。

- 如果，自定义下载文件名为bilibili.name.format = avTitle-numAvId-UpId （应该返回旧AV号）
![image](https://user-images.githubusercontent.com/65488456/112805906-c93c2680-90a8-11eb-9b26-2398a7a91fe6.png)
那么，下载2020-03-13的https://www.bilibili.com/video/BV1rE41157Va?from=search&seid=13993884344891097958 ，文件名结果为   【回形针PaperClip】为什么手机需要人工智能？-95899610-258150656
那么，下载2020-05-15的https://www.bilibili.com/video/BV1kA411t76g ，文件名结果为   【回形针PaperClip】开锁师傅对你的锁做了什么？-328198871-258150656
即使在升级之前，也并未出现AV号。

- 如果，自定义下载文件名为bilibili.name.format = avTitle-numAvId-UpId （应该返回新BV号）
![image](https://user-images.githubusercontent.com/65488456/112807265-461bd000-90aa-11eb-8837-327441f5dc55.png)
那么，下载2020-03-11的https://www.bilibili.com/video/BV1UE411K7yL ，文件名结果为   大连小伙走错车厢滞留武汉 成为战“疫”志愿者-AvId-20165629
那么，下载2020-03-25的https://www.bilibili.com/video/BV1o7411y7v1 ，文件名结果为   金银潭医院院长张定宇：援鄂医护是拯救地球的英雄-AvId-20165629
即使在升级之后，也并未出现BV号。

请问：1）程序中是否会自动转换AV和BV号（或者是B站会自动转换）？2）是否有办法看出视频是否发布于2020年3月23日之前？
抱歉我还不太会下载并部署log，不过这些问题或许不需要log。如果需要，我会尝试补齐log日志。

**Comment by nICEnnnnnnnLee** [comment]
+ BV号和AV号是一对一的，可以相互转换。  
 文件名中没有出现av/bv号，是大小写的问题，`AvId`既不是`avId`，也不是`numAvId`,所以会原文出现。
+ 已知视频av id和cid，是可以知道视频的发布时间的。  
    + 但从最开始就没考虑过要要拿这些信息，在设计的时候就没有加这个字段。  
    + 另一个，在已经实现的这些url解析里面，并不是所有API返回的信息(比如发布时间)都是齐全的，有的有有的没有。  
  要拿的话还要额外再来一次HTTP请求。这会加大HTTP 412的出现力度。
    + 当然最主要的还是嫌麻烦，我觉得实现的性价比不高。

**Comment by nICEnnnnnnnLee** [comment]
下面用一个例子，来说明如何获得某视频的所有分p的详细信息。
需要的话你可以写个脚本什么的自己搞定
+ 根据BV号获取所有p的cid信息
`https://api.bilibili.com/x/player/pagelist?bvid=BV1LB4y1P7L3`
返回数据，拿到这些分P的cid
```json
{
	"code": 0,
	"message": "0",
	"ttl": 1,
	"data": [{
		"cid": 316466870,
		"page": 1,
		"from": "vupload",
		"part": "不列颠尼亚1",
		"duration": 3409,
		"vid": "",
		"weblink": "",
		"dimension": {
			"width": 1920,
			"height": 1080,
			"rotate": 0
		}
	}]
}
```

+ 根据BV号和cid，查询每一个分P小视频的详细信息。
`https://api.bilibili.com/x/web-interface/view?bvid=BV1LB4y1P7L3&cid=316466870`
这些返回信息基本上顾名思义，比如你要的发布日期应该就是`pubdate`
```json
{
	"code": 0,
	"message": "0",
	"ttl": 1,
	"data": {
		"bvid": "BV1LB4y1P7L3",
		"aid": 587324166,
		"videos": 1,
		"tid": 173,
		"tname": "桌游棋牌",
		"copyright": 1,
		"pic": "http://i2.hdslb.com/bfs/archive/e9687f0fc3aef6b7f94e0714f3722ab54c649111.jpg",
		"title": "【（桌游）不列颠尼亚】不列颠的千年史诗（上）",
		"pubdate": 1616934130,
		"ctime": 1616934131,
		"desc": "新浪微博：http://weibo.com/u/2538686360\n书店：https://h5.youzan.com/v2/showcase/homepage?alias=j085tepy\n直播间：https://live.bilibili.com/473\n遇到引战弹幕请举报，请勿与他对喷，我会尽最大努力维持一个和谐的弹幕环境",
		"state": 0,
		"duration": 3409,
		"mission_id": 16420,
		"rights": {
			"bp": 0,
			"elec": 0,
			"download": 1,
			"movie": 0,
			"pay": 0,
			"hd5": 1,
			"no_reprint": 1,
			"autoplay": 1,
			"ugc_pay": 0,
			"is_cooperation": 0,
			"ugc_pay_preview": 0,
			"no_background": 0,
			"clean_mode": 0,
			"is_stein_gate": 0
		},
		"owner": {
			"mid": 1276787,
			"name": "稚嫩的魔法师",
			"face": "http://i2.hdslb.com/bfs/face/d10f73e58f0fb1fa1df7c2524bf92e6a7bf7be16.jpg"
		},
		"stat": {
			"aid": 587324166,
			"view": 88700,
			"danmaku": 2250,
			"reply": 362,
			"favorite": 1118,
			"coin": 2801,
			"share": 177,
			"now_rank": 0,
			"his_rank": 0,
			"like": 5788,
			"dislike": 0,
			"evaluation": "",
			"argue_msg": ""
		},
		"dynamic": "",
		"cid": 316466870,
		"dimension": {
			"width": 1920,
			"height": 1080,
			"rotate": 0
		},
		"no_cache": false,
		"pages": [{
			"cid": 316466870,
			"page": 1,
			"from": "vupload",
			"part": "不列颠尼亚1",
			"duration": 3409,
			"vid": "",
			"weblink": "",
			"dimension": {
				"width": 1920,
				"height": 1080,
				"rotate": 0
			}
		}],
		"subtitle": {
			"allow_submit": true,
			"list": []
		},
		"user_garb": {
			"url_image_ani_cut": ""
		}
	}
}
```
