### ISSUE TITLE
收藏夹下载功能，在一个有25个视频选集后面计数不太正常

### ISSUE THREAD

**Issue by vanjune** [nICEnnnnnnnLee/BilibiliDown#66]
**我已经确认**
+ 使用的当前版本为最新版本
+ issue区没有类似的情况（有的话请直接去该问题讨论）

**问题描述**
抓收藏夹，缺了最后的一页多

**相关信息**
+ 当前系统(windows/linux等) win10
+ java版本 未知
+ 相关链接或者BV号 https://www.bilibili.com/video/BV1XE411f7vw
+ 账号是否登录 登录了
+ 在网页端观看是否存在问题 没问题
+ 是否存在自定义parsers 收藏夹，每页100
+ 相关log 
"upper":{"face":"http://i0.hdslb.com/bfs/face/b8c8166b692aed9ecaa076f1cf42cc87cff1c71e.jpg","followed":0,"mid":522811647,"name":"贝妮和Rocky","vip_due_date":1607529600000,"vip_pay_type":0,"vip_statue":0,"vip_type":1}},{"attr":0,"bv_id":"BV1tp411Z73Q","bvid":"BV1tp411Z73Q","cnt_info":{"coin":19,"collect":109,"danmaku":12,"play":6751,"reply":30,"share":56,"thumb_down":0,"thumb_up":45},"coin":{"coin_number":0,"max_num":2},"copyright":1,"cover":"http://i1.hdslb.com/bfs/archive/d43745b8d084218b6f05fca0efd2d556a6802671.jpg","ctime":1526422295,"dimension":{"height":1080,"rotate":0,"width":1920},"duration":98,"elec_open":0,"fav_state":0,"fav_time":1583168870,"id":23484999,"intro":"微信：Jared_Zhangheng\n保持好奇 终身学习 欢迎交流","like_state":0,"link":"bilibili://video/23484999","page":1,"pages":[{"dimension":{"height":1080,"rotate":0,"width":1920},"duration":98,"from":"vupload","id":39170372,"metas":[{"quality":15,"size":6252},{"quality":16,"size":6252},{"quality":32,"size":13852},{"quality":48,"size":17894},{"quality":64,"size":29537},{"quality":74,"size":43012},{"quality":80,"size":43012},{"quality":112,"size":83437},{"quality":116,"size":83437},{"quality":66,"size":24524}],"page":1,"title":"遇到－B站版本"}],"pubtime":1526436020,"rights":{"autoplay":1,"bp":0,"download":0,"elec":0,"hd5":1,"movie":0,"no_background":0,"no_reprint":1,"pay":0,"ugc_pay":0},"short_link":"https://b23.tv/BV1tp411Z73Q","tid":193,"title":"这是你们爱的福建小垦丁 松下GH5小清 新系婚纱MV「遇到」","type":2,"upper":{"face":"http://i2.hdslb.com/bfs/face/93b77eb8f01b087fa970be36a10f517d9af1b88c.jpg","followed":1,"mid":129802844,"name":"张恒1023","vip_due_date":1635782400000,"vip_pay_type":1,"vip_statue":1,"vip_type":2}}]},"message":"success"}

https://space.bilibili.com/114378534/favlist?fid=813468334&ftype=create
当前解析的id为：
ml813468334p=4
ml813468334
MLParser正在获取结果813468334
AbstractPageQueryParser-result/46 : 当前 pageSize: 100, 查询第 4页。 即获取第 301 到第400个视频
--获取收藏夹视频： 第16页 第1 到 第20
MLParser-query/73 : https://api.bilibili.com/medialist/gateway/base/detail?media_id=813468334&pn=16&ps=20
MLParser-query/74 : {"code":0,"data":{"info":{"attr":22,"cnt_info":{"coin":0,"collect":0,"danmaku":0,"play":0,"reply":0,"share":0,"thumb_down":0,"thumb_up":0},"cover":"http://i2.hdslb.com/bfs/archive/96876d96d0cbe148d8b422d2fb28f600c05a089f.jpg","cover_type":2,"ctime":1580376048,"fav_state":0,"fid":8134683,"id":813468334,"intro":"","like_state":0,"media_count":0,"mid":114378534,"mtime":1580381825,"state":0,"title":"神作","type":11,"upper":{"face":"http://i0.hdslb.com/bfs/face/e48952d599dbf011c2235239fafa2bf0deccef5a.jpg","followed":0,"mid":114378534,"name":"越小郡","vip_due_date":0,"vip_pay_type":0,"vip_statue":0,"vip_type":0}}},"message":"success"}

![2021-04-30 010457](https://user-images.githubusercontent.com/46645444/116597574-5993b280-a958-11eb-8717-ec0949350707.png) 可以看到，最后就是这两个视频，一个是『运镜大神 。。。』，然后是『最终不过是擦肩而过 。。。』
![2021-04-30 010408](https://user-images.githubusercontent.com/46645444/116597896-c018d080-a958-11eb-8a7f-3a0bb30f1faf.png)
看一下实际的收藏夹，『运镜大神 。。。』位于倒数第二行的倒数第二个，后面还有一行
![2021-04-30 010444](https://user-images.githubusercontent.com/46645444/116598011-e9396100-a958-11eb-8f87-e32f574d740e.png)
然后还有一页，但软件好像抓不到这么多，差了253-235=18个视频，我觉得可能跟『运镜大神。。。』里面视频太多有关系
![2021-04-30 020409](https://user-images.githubusercontent.com/46645444/116598307-3cabaf00-a959-11eb-95ff-772f4943af52.png)
这个视频链接是 https://www.bilibili.com/video/BV1XE411f7vw

log我看了一下，收藏夹倒数第二页是能全部抓到的，可能解析有一点小问题，最后一页没抓出来

非常感谢你开发了这个软件，感谢！！

**Comment by nICEnnnnnnnLee** [comment]
+ 这是由于已失效视频的json结构异常引起的。  
下载前先清空收藏夹的异常视频可解决这个问题。

<hr/>

当前可以正常解析的已失效视频结构：
```json
{
    "attr": 9,
    "bv_id": "BV1yJ411t7ap",
    "bvid": "BV1yJ411t7ap",
    "cnt_info": {
        "coin": 45234,
        "collect": 38605,
        "danmaku": 15221,
        "play": 1175929,
        "reply": 4664,
        "share": 14931,
        "thumb_down": 0,
        "thumb_up": 56606
    },
    "coin": {
        "coin_number": 0,
        "max_num": 2
    },
    "copyright": 1,
    "cover": "http://i0.hdslb.com/bfs/archive/be27fd62c99036dce67efface486fb0a88ffed06.jpg",
    "ctime": 1576762130,
    "dimension": {
        "height": 1080,
        "rotate": 0,
        "width": 1920
    },
    "duration": 287,
    "elec_open": 0,
    "fav_state": 0,
    "fav_time": 1585417954,
    "id": 79872843,
    "intro": "语音素材 蕊希电台\n视频素材 四重奏",
    "like_state": 0,
    "link": "bilibili://video/79872843",
    "page": 1,
    "pages": [{
        "dimension": {
            "height": 1080,
            "rotate": 0,
            "width": 1920
        },
        "duration": 287,
        "from": "vupload",
        "id": 136698608,
        "metas": [{
            "quality": 15,
            "size": 18310
        }, {
            "quality": 16,
            "size": 18310
        }, {
            "quality": 32,
            "size": 40567
        }, {
            "quality": 48,
            "size": 52406
        }, {
            "quality": 64,
            "size": 86501
        }, {
            "quality": 74,
            "size": 125964
        }, {
            "quality": 80,
            "size": 125964
        }, {
            "quality": 112,
            "size": 244351
        }, {
            "quality": 116,
            "size": 244351
        }, {
            "quality": 66,
            "size": 71821
        }],
        "page": 1,
        "title": "“别去打扰一个不爱你的人”"
    }],
    "pubtime": 1576762130,
    "rights": {
        "autoplay": 1,
        "bp": 0,
        "download": 0,
        "elec": 0,
        "hd5": 1,
        "movie": 0,
        "no_background": 0,
        "no_reprint": 1,
        "pay": 0,
        "ugc_pay": 0
    },
    "short_link": "https://b23.tv/BV1yJ411t7ap",
    "tid": 21,
    "title": "已失效视频",
    "type": 2,
    "upper": {
        "face": "http://i0.hdslb.com/bfs/face/b4b3bf4dc1784da87587379bc32122ca7bdf10c0.jpg",
        "followed": 0,
        "mid": 15885669,
        "name": "阳光明媚的抱抱",
        "vip_due_date": 1611158400000,
        "vip_pay_type": 0,
        "vip_statue": 0,
        "vip_type": 1
    }
}
```

当前不能够正常解析的已失效视频结构：
```json
{
    "attr": 9,
    "bv_id": "BV1fE411F7vg",
    "bvid": "BV1fE411F7vg",
    "cnt_info": {
        "coin": 1306,
        "collect": 4912,
        "danmaku": 210,
        "play": 122280,
        "reply": 0,
        "share": 1769,
        "thumb_down": 0,
        "thumb_up": 4548
    },
    "coin": {
        "coin_number": 0,
        "max_num": 1
    },
    "copyright": 2,
    "cover": "http://i0.hdslb.com/bfs/archive/be27fd62c99036dce67efface486fb0a88ffed06.jpg",
    "ctime": 1584928726,
    "dimension": {
        "height": 0,
        "rotate": 0,
        "width": 0
    },
    "duration": 0,
    "elec_open": 0,
    "fav_state": 0,
    "fav_time": 1585410502,
    "id": 98464825,
    "intro": "https://www.youtube.com/watch?v=\nAUXOUT\n11 分钟前\nI shot this in last autumn but I wasn't able to upload for some reason until now????",
    "like_state": 0,
    "link": "bilibili://video/98464825",
    "page": 0,
    "pubtime": 1584928726,
    "rights": {
        "autoplay": 0,
        "bp": 0,
        "download": 0,
        "elec": 0,
        "hd5": 1,
        "movie": 0,
        "no_background": 0,
        "no_reprint": 0,
        "pay": 0,
        "ugc_pay": 0
    },
    "short_link": "https://b23.tv/BV1fE411F7vg",
    "tid": 21,
    "title": "已失效视频",
    "type": 2,
    "upper": {
        "face": "http://i0.hdslb.com/bfs/face/625b9f79808f5b6297e312fa1f4d67677fa4c6e1.jpg",
        "followed": 0,
        "mid": 345979287,
        "name": "果然紀",
        "vip_due_date": 1591891200000,
        "vip_pay_type": 0,
        "vip_statue": 0,
        "vip_type": 1
    }
}
```
