### ISSUE TITLE
macOS下ffmpeg路径无法生效

### ISSUE THREAD

**Issue by nICEnnnnnnnLee** [nICEnnnnnnnLee/BilibiliDown#70]
**我已经确认**
+ 使用的当前版本为最新版本
+ issue区没有类似的情况（有的话请直接去该问题讨论）

**问题描述**
+ 在app.config修改了ffmpeg路径后，打开软件时提示没有找到ffmpeg，但路径是正确的。
+ 在app.config修改的设置也无法显示在软件的设置页面，直接在软件中设置提示“无法保存“。

_Originally posted by @caperner in https://github.com/nICEnnnnnnnLee/BilibiliDown/issues/32#issuecomment-894091370_
_Originally posted by @Sakuradreancat in https://github.com/nICEnnnnnnnLee/BilibiliDown/issues/32#issuecomment-886632406_

**相关信息**
+ 当前系统(windows/linux等)
Macbook air M1 macOS 11.2
+ java版本
待补充

+ 相关log
  + windows下，运行run-UI-debug.bat，复现以后，复制一下控制台的输出
  + 其它平台，控制台cd到目录后java -Dfile.encoding=utf-8 -jar INeedBiliAV.jar，复现以后，复制一下控制台的输出
待补充

**Comment by nICEnnnnnnnLee** [comment]
> 
> 
> 在app.config修改了ffmpeg路径后，打开软件时提示没有找到ffmpeg，但路径是正确的。

程序运行后会打印相关配置，请贴出对应的log，确认ffmpegPath是否在程序内生效。@caperner
![Q1](https://user-images.githubusercontent.com/19970934/128485523-8b5117d0-90c4-4303-ab98-d8f5ebb775f8.png)

**Comment by yongdono** [comment]
最新发行版自带的配置文件 app.config中, bilibili.ffmpegPath这个键值出现两次，整个文件最后多了一行
bilibili.ffmpegPath=ffmpeg
把那一行删掉就能生效了。

另外，文档中没提到的一点，mac/Linux下文件名的格式也需要修改，即：
bilibili.name.format = (:listName 0_listName\)UpName\avTitle-(:favTime favTime-)pAv2-clipTitle-qn
要改成
bilibili.name.format = (:listName 0_listName/)UpName/avTitle-(:favTime favTime-)pAv2-clipTitle-qn
否则最后保存的文件不会按up主名称等自动创建子目录。
这个bug也可以通过修改代码来修复，即把CmdUtil.java中
private static String genFormatedName(HashMap<String, String> paramMap, String formatStr)
这个方法最后一行从
return sb.toString().replaceAll("[\t\b\\r\\n|:*?<>\"$]", "_");
改成
return sb.toString().replaceAll("[\t\b\\r\\n|:*?<>\"$]", "_")
				.replaceAll("[/\\\\]", File.separator);
