### ISSUE TITLE
下载不成功

### ISSUE THREAD

**Issue by telessa** [nICEnnnnnnnLee/BilibiliDown#72]
**我已经确认**
+ v6.3
+ issue区没有类似的情况

**问题描述**
1 
    个别视频下载任务会无止境的提示 转码中 
手动暂停再试会显示 下载已完成 
但是视频也没有出现对应文件夹中 只有缓存文件出现在download下 缓存视频是完整的
https://www.bilibili.com/video/BV1ix411T7gb?p=3
https://www.bilibili.com/video/BV1ix411T7gb?p=4
https://www.bilibili.com/video/BV1Qx411P7aW?p=1
https://www.bilibili.com/video/BV1Xx411n7oX?p=3
https://www.bilibili.com/video/BV1Zx411N7Yj?p=6
https://www.bilibili.com/video/BV1Zx411N7Yj?p=7

2
个别视频提示下载成功 视频时长与网页一致50:08 但是视频从45：55缺失 网页可以正常放下去的 
 https://www.bilibili.com/video/BV1ix411T7gb?p=3

**相关信息**
+ Windows 10 21H1 19043.1165
+ java版本 (工作版本 1.8.0_301-b09)
+ 账号是否登录 是
+ 在网页端观看是否存在问题 没有

下载文件时，分{count}部分同时下载
## 0 或 1 为不开启多线程下载
bilibili.download.multiThread.count = 9
# 当下载链接匹配该正则时，不进行多线程下载
bilibili.download.multiThread.singlePattern = github|ffmpeg|\.jpg|\.png|\.webp|\.xml

如果视频地址打不开 在地址栏回车

**Comment by nICEnnnnnnnLee** [comment]
+ 这是一个bug，在下载陈年老物时可能会出现。  
+ 问题在于在合并分段的flv文件时有可能陷入死循环，之后导致一系列的不服预期的状况。  
   + 该问题会在下个版本解决
   + 一个临时的解决方案是，使用ffmpeg合并flv文件，修改配置如下：
     ```
     bilibili.flv.ffmpeg = true
     ```
