### ISSUE TITLE
白蛇2链接无法解析

### ISSUE THREAD

**Issue by scientificCommunity** [nICEnnnnnnnLee/BilibiliDown#74]
首先感谢大佬的作品！

**我已经确认**
+ 使用的当前版本为最新版本
+ issue区没有类似的情况（有的话请直接去该问题讨论）

**问题描述**
请尽量详细地描述问题，以告诉如何复现，方便定位问题。

**相关信息**
+ 当前系统windows
+ java版本:java8
+ 相关链接或者BV号:[链接](https://www.bilibili.com/bangumi/play/ep419527?theme=movie%3Ffrom%3Dsearch&seid=6242844942515636071&spm_id_from=333.337.0.0)
+ 账号是否登录：已登录
+ 在网页端观看是否存在问题：无
+ 是否存在自定义parsers
+ 相关log
  + windows下，运行run-UI-debug.bat，复现以后，复制一下控制台的输出
  + 其它平台，控制台cd到目录后java -Dfile.encoding=utf-8 -jar INeedBiliAV.jar，复现以后，复制一下控制台的输出

**Comment by scientificCommunity** [comment]
貌似b站的数据协议改了

**Comment by nICEnnnnnnnLee** [comment]
`V5.8` 支持自定义各种链接解析；
`V5.9` 不再支持番剧下载

**Comment by scientificCommunity** [comment]
> `V5.8` 支持自定义各种链接解析；
> `V5.9` 不再支持番剧下载

好嘞！
