### ISSUE TITLE
[Feature requests]文件命名格式增加视频收藏时间

### ISSUE THREAD

**Issue by arisazero** [nICEnnnnnnnLee/BilibiliDown#76]
**我已经确认**
+ 使用的当前版本为最新版本
+ issue区没有类似的情况（有的话请直接去该问题讨论）

**问题描述**
想要将下载的视频按收藏夹内的顺序排序,目前可用的方法是以'pDisplay'命名视频,但是这种方法在收藏夹新增视频后会产生重复的pn1,pn2,pn3...

**Comment by nICEnnnnnnnLee** [comment]
当净点赞值>=6时开始开动
