### ISSUE TITLE
新版本登录窗口有奇怪问题

### ISSUE THREAD

**Issue by 2651084156** [nICEnnnnnnnLee/BilibiliDown#84]
如图
![图片](https://user-images.githubusercontent.com/69307837/144710613-dac12b75-eafb-4792-b131-fa788e1a213e.png)
![图片](https://user-images.githubusercontent.com/69307837/144710681-6263b25f-af2a-4f92-b615-bf4e3e4f0b0f.png)
基本上输入不了验证码

其他地方也有这种问题
![图片](https://user-images.githubusercontent.com/69307837/144710729-83658806-790b-4878-af65-6909d0206635.png)

**Comment by nICEnnnnnnnLee** [comment]
请尽可能多的提供相关信息，比如当前系统和java版本等。
标题是**新版本**有奇怪问题，我猜你可能用过某个旧版本？  
那么在你的环境下最后一个排版没有问题的版本是哪个呢？

**Comment by 2651084156** [comment]
> 
java
![图片](https://user-images.githubusercontent.com/69307837/144714379-f40286ac-ca22-4756-87cc-68193c1c1213.png)

最后一个没问题的应该是是6.4
因为6.4自动更新失败了所以是手动下载的6.7然后扔其他目录使用的

系统版本
![图片](https://user-images.githubusercontent.com/69307837/144714461-87894fd2-f662-43f3-b7b5-119f0e5cb774.png)

**Comment by 2651084156** [comment]
> 请尽可能多的提供相关信息，比如当前系统和java版本等。 标题是**新版本**有奇怪问题，我猜你可能用过某个旧版本？ 那么在你的环境下最后一个排版没有问题的版本是哪个呢？

看起来是登录的问题登录完以后重启软件就好了
如果退出登录一输入账号就又会出现

**Comment by chencxt** [comment]
版本6.8，电脑惠普暗夜精灵4pro（笔记本）
我来说个比较奇怪的解决方法（使用密码登录依旧不行）：
1，退出登录
2，在配置面板使用“默认qr登录”
3，保存配置并重启
4，手机扫码后可以正常进入使用
就，挺离谱
