### ISSUE TITLE
总是显示已下载过该视频

### ISSUE THREAD

**Issue by andrew2558** [nICEnnnnnnnLee/BilibiliDown#86]
**我已经确认**
- [ * ] 使用的当前版本为最新版本
- [ * ] issue区没有类似的情况（有的话请直接去该问题讨论）

**问题描述**
下载播放列表，总有一两个视频显示已下载过该视频

**相关信息**
+ 当前系统(windows/linux等)
+ java版本
+ 相关链接或者BV号
+ 账号是否登录
+ 在网页端观看是否存在问题
+ 是否存在自定义parsers
+ 相关log
  + 如何抓log请参考[Wiki-How to log](https://github.com/nICEnnnnnnnLee/BilibiliDown/wiki/How-to-log)

```
请在发表issue前进行预览，将影响排版的内容放到这里
```

**Comment by nICEnnnnnnnLee** [comment]
我没能理解`下载播放列表`具体是什么操作。  
另外，你是否下载过提示的视频呢？ 是不想要这个提示，还是没下载但提示了？

**Comment by andrew2558** [comment]
下载播放列表就是下载bilibili的播放清单（多个视频一起），有的视频（清单中的某一个或几个）会弹框提示已下载过该视频
但该视频的确是没有下载过的，下载的缓存也删了，目标文件夹下也没有该视频。

**Comment by nICEnnnnnnnLee** [comment]
> 但该视频的确是没有下载过的，下载的缓存也删了，目标文件夹下也没有该视频。

+ 首先要确认一点，并不是把已完成的下载或者下载的缓存删掉了，这个视频就叫没下载过了。如果我们就这一点达成共识，那么继续。  

+ 其次，下载记录是以BV号+分P序号定位的，如果下载过的视频内容出现过变动，遇到这种情况只能手动删除记录或者取消检测功能。
比如原BV666下1p、2p俩个视频，我下载了，然后up主把2p删掉，又新增2p、3p，
那么批量下载会提示BV666-1p、BV666-2p已下载，需要人工删除BV666-2p的记录或者取消检测功能。
如果是这种情况，那也没啥好说的，我不打算改。

+ 如果以上都不是，那么情况会稍显复杂，需要更多的信息用于定位。  
    + 为了便于交流与配合，我先大概讲一下原理：
      程序会维护一个已下载记录，这个记录和文件`config/repo.config`同步；  
      在下载任务开始前，会先判断是否在记录里；    
      当下载任务完成后，会进行记录追加。
    + 我再举一个例子我需要什么样的信息用于问题复现与定位：  
```
    我使用链接https://space.bilibili.com/56547276/video 下载UP主合集 
    分页查询时每页大小为5，(不知道可以略过)
    以前已经把合集下过一遍，已下过的UP主合集里最新的视频是BV1234567(能提供最好，不知道就算了)
    现在追更，下载UP主合集第一页时，提示 BV7654321-p2已经下载。
    我确认下载目录没有BV7654321-p2的视频或缓存。
    我确认文件config/repo.config里面有？没有？BV7654321-p2的记录。
```

**Comment by andrew2558** [comment]
首先，非常感谢你的耐心解答。
其实我使用的情况没有你上面说的那么复杂，我想是repo.config里有了，而视频又没有下载。
（之前不知道有repo.config这个文件以及作用）
感谢！！！ @nICEnnnnnnnLee
