### ISSUE TITLE
出新bug了,下载有时候出现下载异常

### ISSUE THREAD

**Issue by daofeng2015** [nICEnnnnnnnLee/BilibiliDown#9]
![20190509230516](https://user-images.githubusercontent.com/14891398/57464392-383ee500-72af-11e9-99f5-53ebf7d71149.jpg)

**Comment by LoveSavedTheWorld** [comment]
+ 先说一下，`继续下载`会在上一次的进度上继续，不是重新开始Ծ‸Ծ

+ 这是一个问题，但还没想好怎么处理好😂😂现在的做法是直接下载整个文件`byte=begin-`，没有分段，长连接断掉的话算是在预期内，也绕不过去。我在想是不是加一个自动重连机制

**Comment by nICEnnnnnnnLee** [comment]
:grinning: 现在[V3.6](https://github.com/nICEnnnnnnnLee/BilibiliDown/releases/tag/V3.6)会把下载失败的那些再捡起来放进下载队列，省掉了人工点`继续下载`的按钮的过程

**Comment by asionxu** [comment]
现在下载全是下载异常。ToT

**Comment by nICEnnnnnnnLee** [comment]
∠( ᐛ 」∠)＿

**Comment by nICEnnnnnnnLee** [comment]
@asionxu 老铁，不在电脑旁边，麻烦选个异常的单独下载试一下，看看是api解析 还是网络波动的问题😂

用目录下的这个打开程序`run-UI-dubug.bat`

**Comment by asionxu** [comment]
OK，我现在去试一下

**Comment by asionxu** [comment]
知道原因了，release的版本里没有ffmpeg.exe，所以一直转码失败，下一个ffmpeg.exe放到路径下就好了。

**Comment by xihadandan** [comment]
下载异常
![image](https://user-images.githubusercontent.com/15681750/68570535-e95f4b80-049b-11ea-92d9-94423fa87e6d.png)
