### ISSUE TITLE
三个问题

### ISSUE THREAD

**Issue by iamPorter** [nICEnnnnnnnLee/BilibiliDown#95]
三个问题：
1.它不能直接通过双击JAR打开；2.它不能下载同一个视频的不同分辨率，哪怕是下载的文件手动删除了也不能进行（虽然说不让重复下载是出于防止重复下载的保护措施）；3.非会员环境下选择下载1080p+及更高的需要会员的清晰度的视频时程序不会根据全局默认设定下载，只会下载720p的标准帧率版
**相关信息**
+ Windows 10 家庭中文版
+ Java 1.8.0u331和1.7(都是64位版)
+ 所有视频都有这问题
+ 没有登录
+ 和网页端没关系
+ 不存在自定义parsers
+ 第一个问题：程序都启动不了抓不到log；2、3问题：这问题不需要分析log吧？

**Comment by nICEnnnnnnnLee** [comment]
> 它不能直接通过双击JAR打开

我也很惊讶会被问到这么个问题。
如果以默认编码方式打开程序可能会出现乱码。
另外，在Windows系统下某个扩展双击用什么东西打开这不是本项目关心的问题。  

> 它不能下载同一个视频的不同分辨率

你可以用记事本打开`config/app.config`文件，将`bilibili.repo = on`改成`bilibili.repo = off`。
或者可以在程序`右上角菜单-> 配置 -> 打开配置页`找到相应选项


> 非会员环境下选择下载1080p+及更高的需要会员的清晰度的视频时程序不会根据全局默认设定下载，只会下载720p的标准帧率版

这一表现符合预期。

**Comment by iamPorter** [comment]
第一个问题就暂且说是电脑Java有安装问题吧
不过就第三个问题而言，我想着其它本地分析程序是可以在不登陆的情况下分析下载1080p30的视频的，但该程序在选定1080p时好像也不会下载1080p30的视频只会下载720p30的视频（可能我当时写issue时还没试过1080p）
这点很奇怪，因为网页端是非登录只能看480p，登录能看1080p30，其它下载器也是不登录能下载1080p30，而这个程序奇怪地选用720p。

**Comment by nICEnnnnnnnLee** [comment]
如果你认为下载清晰度不符合预期，请提供具体BV号。

**Comment by nICEnnnnnnnLee** [comment]
简单看了俩，未登录预期清晰度实际上是480p，B站api返回720p已经超过期望了。
![BV1TT4y197QK](https://user-images.githubusercontent.com/19970934/171314025-b9bd40f7-1840-42bd-ab18-f8ded55b560e.jpg)

![BV1AW4y1C7vC](https://user-images.githubusercontent.com/19970934/171314044-6fe41326-afba-4044-8ce5-73b3015d39f1.jpg)

---
如果你对此不满意，可以参考[Henryhaohao/Bilibili_video_download/issues#87](https://hub.fastgit.xyz/Henryhaohao/Bilibili_video_download/issues/87#issuecomment-819607812)，实现自定义链接解析parsers，本项目不会采用这种方式。
