### ISSUE TITLE
字幕下载异常，视频下载没问题

### ISSUE THREAD

**Issue by shin701** [nICEnnnnnnnLee/BilibiliDown#98]
**我已经确认**
- [ ] 使用的当前版本为最新版本
- [ ] issue区没有类似的情况（有的话请直接去该问题讨论）

**问题描述**
请尽量详细地描述问题，以告诉如何复现，方便定位问题。

**相关信息**
+ 当前系统(windows/linux等)
+ java版本
+ 相关链接或者BV号
+ 账号是否登录
+ 在网页端观看是否存在问题
+ 是否存在自定义parsers
+ 相关log
  + 如何抓log请参考[Wiki-How to log](https://github.com/nICEnnnnnnnLee/BilibiliDown/wiki/How-to-log)

```
请在发表issue前进行预览，将影响排版的内容放到这里
```

**Comment by nICEnnnnnnnLee** [comment]
请提供更具体的信息，我这边测试了一下`av34218168`，没有发现问题。
